### ISSUE TITLE
accept BOWER_FLAGS like NPM_FLAGS and YARN_FLAGS

### ISSUE THREAD

**Issue by fool** [netlify/build-image#108]
since there is no way to NOT run bower install if there is a /bower.json - we should allow users to pass flags like we do for NPM and YARN

**Comment by c0b41** [comment]
Bower deprecation soon also yarn support bower installing https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by brycekahle** [comment]
Bower is actively encouraging folks to migrate to yarn. I do not think we should add new features for it.

**Comment by oskarrough** [comment]
For anyone ending up here from a search. Older versions of bower use a registry that might fail on Netlify with a "EINVRES failed 502" error.

If you can't upgrade bower, tell bower to use the new registry with a `.bowerrc` file. Like this:

```
{
  "registry": "https://registry.bower.io"
}
```
