### ISSUE TITLE
How to duplicate the exact command used

### ISSUE THREAD

**Issue by gitleet** [netlify/build-image#118]
Hello,
What is the exact command that will be used on netlify when there is a git webhook?

I want to ensure my build that I am testing will be done the same way on your end.

**Comment by fool** [comment]
You can walk through exactly what happens here:

https://github.com/netlify/build-image/blob/master/run-build-functions.sh

The only piece that happens "outside that" is the initial git clone which creates the repository directory and happens using the deploy key that is installed in your repository settings.  That looks like this:

`git clone <your project> ; cd <project checkout> && git submodule update -f --init`

**Comment by fool** [comment]
If you want more information, please write into support@netlify.com -these are intended to be bug reports and feature requests :)
