### ISSUE TITLE
cache python dependencies correctly

### ISSUE THREAD

**Issue by fool** [netlify/build-image#119]
This doesn't happen at present (as it does for Ruby, Node, and soon to be clojure)

**Comment by brycekahle** [comment]
We are caching the pip `.cache` directory. Is there something more needed?

**Comment by fool** [comment]
It didn't seem to work last time we tested it.  I don't know what else is needed but I do trust the handful of reports we got to this effect.  I'll get a repro case before bringing it back to you.

Customers who use python in their builds please let me know if you have one!

**Comment by brycekahle** [comment]
@fool why did you reopen this? I actually found a code fix, hence why the commit closed it.

**Comment by fool** [comment]
Sorry - what I read in your comment is that "we are already doing this" which customers said was not the case, so I assigned it to myself to find a repro case that I could present you with rather than "asserting it to be so" which is what the initial filing was about!

Sorry - I now see that you closed it via code change, re-closing until we get some other report of misbehavior
