### ISSUE TITLE
Update yarn

### ISSUE THREAD

**Issue by nicooprat** [netlify/build-image#122]
I'm seeing this message in deploy details: `Installing NPM modules using Yarn version 0.18.1`. Is there any reason to use an old yarn version? Latest is [1.3.2](https://github.com/yarnpkg/yarn/releases/tag/v1.3.2).

**Comment by rybit** [comment]
Hi - that is just the default that is pinned in the image (legacy thing). You can set the `YARN_VERSION` in your project to keep up with the latest yarn. If you get stuck ping support and we can help you along.
