### ISSUE TITLE
Builds fail with "fork/exec /usr/local/bin/build: no such file or directory"

### ISSUE THREAD

**Issue by arekkas** [netlify/build-image#127]
I can not execute builds on the netlify platform, I receive the following error:

```
4:14:15 PM: Build command unable to start
4:14:15 PM: Error running command: fork/exec /usr/local/bin/build: no such file or directory
```

I ran a debug build based on [this guide](https://www.netlify.com/docs/build-gotchas/) which worked without any issues.

**Comment by brycekahle** [comment]
@arekkas Can you contact support? They can help you solve your build problems.

**Comment by arekkas** [comment]
Ok! By the way, I was able to resolve it - seems that build images don't get booted when master branch doesn't use a build pipeline. In my case, I was using a branch and introduced a build pipeline to it.

**Comment by brycekahle** [comment]
@arekkas That is curious. Can you provide more details to make sure that isn't a problem on our end?

**Comment by arekkas** [comment]
Hm, I'm not entirely sure. I have a `netlify.toml` file in the project root:

```toml
[build]
  base    = "public"
  publish = "public"
  command = "yarn build"
```

With that file, the build fails. If I remove the file and set those settings in the Netlify UI then the build succeeds. If I remove those settings from the Netlify UI then the build succeeds as well, but is obviously not built.

I have two branches:

* `master`: Does not use build process (just some static html files)
* `new-site`: Uses gatsby/node to build the website

I am seeing these issues in the PR build preview. Does that help?

**Comment by brycekahle** [comment]
@arekkas Are you sure you want the `base` to be `public`? Normally `public` is an output directory, and not where you want to issue build commands.

**Comment by arekkas** [comment]
Oh, removing base resolves the error! The error message is quite misleading, maybe this could be improved?

**Comment by brycekahle** [comment]
We can look into it, but at that point it is in a bash script so it isn't trivial.
