### ISSUE TITLE
Upgrade to recent yarn by default

### ISSUE THREAD

**Issue by fool** [netlify/build-image#128]
right now you can set YARN_VERSION as desired but then you will almost certainly clash with the `--ignore-optional` we have as default to cope with problems in our current version.

When updating, make sure we do something conditional to preserve the behavior of older builds pinned at yarn 0.18.1

**Comment by fool** [comment]
wow, this happened a couple days ago almost by accident.  There's some additional work to do around here:  https://www.netlify.com/docs/build-gotchas/#yarn - we need to not set --ignore-optional by default for yarn >1.3.2 (Support has seen dozens of cases of this breaking builds - some new, some upgraded from our old default).  But that work needs to be in a different repo, so closing and moving there.

**Comment by brycekahle** [comment]
I think there is still work to be done here: https://github.com/netlify/build-image/blob/master/Dockerfile#L163
