### ISSUE TITLE
broken pkg-config prevents recompilation (at least) of node-gyp using libvips

### ISSUE THREAD

**Issue by fool** [netlify/build-image#139]
Builds that need to compile node-gyp will all struggle with this bug, no matter what version of yarn they use:

https://github.com/lovell/sharp/issues/614

The "fix" is updating pkg-config, which I understand may be problematic.  But this package is not particularly rare and everyone trying to use it will suffer.  In particular a very dear well-paying customer is impacted  (see https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/14675458658).

The error that is produced is this:

```
5:40:15 PM: readelf: Error: '/usr/local/lib  /libvips-cpp.so': No such file
```

and that extra space is due to a bug in pkg-config as shipped with ubuntu 14.04, but it beaks node-gyp's (admittedly byzantine) build sequence.

**Comment by brycekahle** [comment]
@fool Do you know which version of pkg-config is broken, and which version fixes it?

**Comment by fool** [comment]
from my reading of the linked issue on sharp, 0.26 is broken as it ships with ubuntu 14.04, and 0.29 fixes it.  Look at the [very bottom of the conversation there](https://github.com/lovell/sharp/issues/614#issuecomment-256979355) for my source of info

**Comment by brycekahle** [comment]
So that thread indicates `sharp` is handling the broken pkg-config in v0.17.0. Has that been tried?

**Comment by fool** [comment]
That will be our fix and our suggestion to future customers experiencing it.  Thanks for the investigation!
