### ISSUE TITLE
Add nasm

### ISSUE THREAD

**Issue by dmgawel** [netlify/build-image#140]
Newest version of https://www.npmjs.com/package/mozjpeg which is a dependent of many loaders and tasks related to image compression requires Netwide Assembler. As far as I'm concerned nasm is not included in your build-image (we've encountered some broken builds on Netlify). It could be useful :-)

See: https://github.com/imagemin/mozjpeg-bin/issues/35

**Comment by brycekahle** [comment]
This is live!

**Comment by dmgawel** [comment]
Perfect, thank you!
