### ISSUE TITLE
How to use PHP composer in build script?

### ISSUE THREAD

**Issue by minthemiddle** [netlify/build-image#146]
Pull Request https://github.com/netlify/build-image/pull/135 says it fixed using `composer` (referencing https://github.com/netlify/build-image/pull/102).

However I still fail to use `composer` in my build script.

This is what I tried in `netlify.toml`:

- `command = "composer install`-> `composer not found`
- `command = "/opt/buildhome/.phpbrew/bin/composer install`-> `composer not found`

How to use composer to require missing PHP packages in my build script?

**Comment by brycekahle** [comment]
If you have a `composer.json` file, then the build will automatically install them for you. See https://github.com/netlify/build-image/blob/master/run-build-functions.sh#L434-L438

**Comment by brycekahle** [comment]
@minthemiddle My apologies. It looks like the composer install itself got lost in the mix.

**Comment by minthemiddle** [comment]
@brycekahle Ah, I thought I forgot something. Just using `composer.json` will be very nice, once it works…

**Comment by brycekahle** [comment]
@minthemiddle This is not your mistake. I'm fixing the build image now to install composer.

**Comment by brycekahle** [comment]
I'll ping you again when this is live in production.

**Comment by brycekahle** [comment]
@minthemiddle OK, give it a shot now and let me know how it goes.
