### ISSUE TITLE
How to use PHP v7 in build script?

### ISSUE THREAD

**Issue by minthemiddle** [netlify/build-image#147]
https://github.com/netlify/build-image/pull/135#issuecomment-363574565 says that using PHP 7.2.2 is now "just another env var to pass" (after successful PR https://github.com/netlify/build-image/pull/135).

This is what I tried in `netlify.toml`:

```
[build]

PHP_VERSION="7.2.2"
```

And this is what the build logs tell me:

```
9:55:29 PM: Using PHP version 5.6
```
No further reference to `PHP` can be found in the logs. Obviously, `PHP7.2.2` does not get used.

What do I need to change to get `PHP7` running on the build?

**Comment by brycekahle** [comment]
Try using `PHP_VERSION=7.2`. They are aliased via their minor versions only.

**Comment by brycekahle** [comment]
@minthemiddle Did you try using what I suggested?

**Comment by minthemiddle** [comment]
Yes, works.

This is the `netlify.toml` that builds a [Jigsaw (Laravel based)](http://jigsaw.tighten.co/docs/installation/) page successfully now:

```
[build]

PHP_VERSION=7.2

command = "./vendor/bin/jigsaw build production"
publish = "build_production"
```

Wonderful! Thanks @brycekahle

**Comment by typhoon2099** [comment]
I'm trying to set PHP_VERSION in my netlify.toml file but I'm still stuck using 5.6. What format should the environment variable be and what are the accepted values? I've tried `7.2`, `"7.2"`, `7.0`, `"7.0"` and `7`, none of which have worked. Here's my current netlify.toml file:

```
[build]
PHP_VERSION=7.2

command = "php ./scraper.php && yarn build"
publish = "_public"
```

**Comment by minthemiddle** [comment]
This is exactly how I set up my `netlify.toml` file. I had some problems with that as well, so I set the env var in the Netlify backend which has worked flawlessly.

![screen shot 2018-02-24 at 13 22 16](https://user-images.githubusercontent.com/1950766/36630394-fb23960a-1965-11e8-9433-0843e388bb02.png)

**Comment by typhoon2099** [comment]
Huh, that did it. There must be something preventing my netlify.toml file form being read properly. I shall investigate.

**Comment by raniesantos** [comment]
My site is Jigsaw generated and the php version isn't being read from the toml file
```
[build]
PHP_VERSION=7.2
command = "npm run production"
publish = "build_production"

```

**Comment by minthemiddle** [comment]
@raniesantos Define it in Netlify's settings. See this answer here: https://github.com/netlify/build-image/issues/147#issuecomment-368224909

**Comment by raniesantos** [comment]
@minthemiddle thanks for replying. Like I said I already know you can set it manually there.

I just wanted to confirm if setting the PHP version in the toml file is no longer supported for some reason.

Because I read your Medium article and it seems to still be fairly recent so it confuses me why it doesn't completely work as you stated in that post.

**Comment by minthemiddle** [comment]
@raniesantos `netlify.toml` not recognizing `PHP_VERSION=7.2` seems to be a bug that is still not fixed. I will try to reproduce with a few setups and write a bug report, so @brycekahle can solve it :)

**Comment by linuxjuggler** [comment]
hey @minthemiddle  and @raniesantos to set the PHP version you need to use the environment section within the context like this for example

```
[build]

command = "npm run production"
publish = "build_production"

[context.production.environment]

PHP_VERSION="7.2"
```

which gave me the following (as expected) when building my site:
```
7:10:57 PM: Using PHP version 7.2
```

**Comment by raniesantos** [comment]
Cool, I will try this out with a fresh Jigsaw install tomorrow.

**Comment by linuxjuggler** [comment]
@raniesantos  mostly because it's not one of the predefined variables they read, based on [this](https://www.netlify.com/docs/continuous-deployment/#build-environment-variables) not so sure.

but also I found out that you can specify the environment for the build like this:

```
[build]

command = "npm run production"
publish = "build_production"

[build.environment]

PHP_VERSION="7.2"
```

you can read more about the **netlify.toml** file and the sets that can be used from this [doc post](https://www.netlify.com/docs/netlify-toml-reference/)
