### ISSUE TITLE
PHP extension for encodings (UTF-8) missing

### ISSUE THREAD

**Issue by minthemiddle** [netlify/build-image#149]
[`mbstring`](http://php.net/manual/de/intro.mbstring.php) handles encodings in PHP. If any package uses UTF-8, it needs `mbstring`.

It is not yet in the build image. Many projects based on Symfony or Laravel will not build.

Adding it could be as simple as `sudo apt-get install php7.2-mbstring`. For some strange reasons, PHP core does not require it, despite 80% of modern PHP packages depend on it.

Could create a PR as well.

**Comment by brycekahle** [comment]
This is live in production now. Thanks for putting PHP through its paces!

**Comment by minthemiddle** [comment]
Works flawlessly! Great work @brycekahle
