### ISSUE TITLE
accept common config files in unexpected case

### ISSUE THREAD

**Issue by fool** [netlify/build-image#150]
For customers who work on OSX or Windows, the filesystem is not case sensitive.  We can't do much about references in their code that are case-sensitive, but we can improve ours.

$customer recently had a /gemfile in their repo and we don't notice it:

https://github.com/netlify/build-image/blob/master/run-build-functions.sh#L286

I realize this is the norm and technically correct - but it's also unexpected for customers who don't usually develop in case-insensitive environments that: "bundle install works great on my Mac using this file, but it doesn't seem like Netlify even runs it at all?"

Feel free to close WONTFIX if you feel strongly, just wanted to suggest it.

**Comment by brycekahle** [comment]
My opinion is this is not worth the complexity it would introduce.
