### ISSUE TITLE
Add support for Pipenv

### ISSUE THREAD

**Issue by jessebmiller** [netlify/build-image#151]
If there is a Pipenv/Pipenv-lock file install dependencies with Pipenv.

If this is something you'd accept, I may be up for working on it.

**Comment by brycekahle** [comment]
@jessebmiller Do you have any data on how popular `pipenv` is? I see python.org is now recommending it.

**Comment by jessebmiller** [comment]
I don't have data on that, but with further research it looks like it's really just the `Pipfile` and `Pipfile.lock` formats that need support. `pipenv` is just the tool people are using until it's what `pip` supports it.

"Pipfile and its sister Pipfile.lock are a replacement for the existing standard pip's requirements.txt file."
- https://github.com/pypa/pipfile

**Comment by jessebmiller** [comment]
Maybe this issue should be renamed to "Support Pipfile"

**Comment by jayvdb** [comment]
Pipenv is a toml file, so quite a comfortable format for Netlify to inspect, and it includes the Python runtime

```
[requires]

python_version = "3.6"
```

It would be nice to use that instead of `runtime.txt`

**Comment by jessebmiller** [comment]
That's wonderful!
