### ISSUE TITLE
Contexts ?

### ISSUE THREAD

**Issue by aphecetche** [netlify/build-image#156]
Hi,

I'm a bit confused. Can this image / script set be used to reproduce what's being done for a given context ? Said otherwise : is the netlify.toml used in any way ?

**Comment by brycekahle** [comment]
The `netlify.toml` is parsed and handled by the closed-source software that is deployed alongside these scripts. Deploy contexts are used to control the command, environment variables, and any other settings used for a build. If you know what those are, you can replicate what will be done using this repo.

**Comment by aphecetche** [comment]
ok, so the netlify.toml is not used but has to be "simulated" in some way.
thanks.
