### ISSUE TITLE
Allow avoiding npm/pip/gem/whatever install

### ISSUE THREAD

**Issue by airtonix** [netlify/build-image#159]
For pure static deployments where the build step is preferred to happen privately allow us to disable any npm/yarn/pip/gem install step.

essentially there will be an environment variable that control install and skip straight to build command, which would be something like: 

```
[build]
  base    = ""
  publish = "output/"
  command = "mkdir -p output/static/theme && cp -R ./Static/Theme output/static && cp -R ./Static/styleguide output/" 
```

Our situation is like this because the styleguide uses frontend assets served by the actual production website. so we need to copy files around to serve on netlify (and our own internal styleguide nginx server).

- we use private docker images specific to the project to generate our frontend and styleguide.
- our git repo contains production ready assets.
- At the moment a deploy takes 3mins.
- Disabling auto npm install would shave that off.

**Comment by brycekahle** [comment]
Thanks for suggesting this idea. This sounds like an extension of #141 so I'm going to close this in favor of that.
