### ISSUE TITLE
Can I use a new version of pandoc?

### ISSUE THREAD

**Issue by MatchaChoco010** [netlify/build-image#162]
I want to use the [`hexo-katex`](https://github.com/thcd/hexo-katex) package to display TeX formulas on my blog.
And I got the following error message.

```
12:03:13 AM: Executing user command: hexo generate
12:03:13 AM: INFO  Start processing
12:03:14 AM: FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
12:03:14 AM: Error: pandoc exited with code 2: pandoc: unrecognized option `--katex'
12:03:14 AM: Try pandoc --help for more information.
12:03:14 AM:     at ChildProcess.<anonymous> (/opt/build/repo/node_modules/hexo-renderer-pandoc/index.js:84:20)
12:03:14 AM:     at emitTwo (events.js:126:13)
12:03:14 AM:     at ChildProcess.emit (events.js:214:7)
12:03:14 AM:     at maybeClose (internal/child_process.js:925:16)
12:03:14 AM:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

`hexo-katex` requires a pandoc that supports katex (>= version 1.13.2).
The build image pandoc version is 1.12.2.1.

**Comment by brycekahle** [comment]
Unfortunately, that is the latest version available in Ubuntu 14.04. See https://packages.ubuntu.com/trusty/pandoc.

**Comment by MatchaChoco010** [comment]
Oh, I see. Okay, I will give up using `hexo-katex`.
Anyway, thank you for the information.

**Comment by mb21** [comment]
There is also an official .deb of the newest version available for download, see https://pandoc.org/installing.html#linux

Or as a dockerfile: https://github.com/pandoc/dockerfiles
