### ISSUE TITLE
always show build command in output

### ISSUE THREAD

**Issue by fool** [netlify/build-image#166]
It seems that in case someone has a netlify.toml, we don't show the build command anywhere or save it in the DB where Support could look for it.

Could we always show it in the logs before running as we do if there is no toml?

```
4:43:35 PM: Executing user command: middleman build ; cp _redirects mediakit.html build/
```

@fool can give you an example deploy of both the "toml overrides UI settings" and the "toml doesn't override UI settings" which both show the behavior.

**Comment by brycekahle** [comment]
@fool I'm confused. We do show the exact command we are going to run in the logs.

**Comment by fool** [comment]
I wish I'd linked a build without one.  There was some case where it was never shown.  I'll mark this as needs_reproduction until I see another one.

**Comment by brycekahle** [comment]
Copying comment incorrectly posted by @fool to another issue:

> unable to reproduce, closing.
>
> I tested:
> 
> set in UI only
> set in toml only
> set in UI + toml differently
> set in UI + toml same
> all showed the command somewhere. It isn't all in the "same place" - some nearer > the top of the deploy and some kinda in the middle - but it's always there and that's good enough for me.
