### ISSUE TITLE
Install fonttools in build image

### ISSUE THREAD

**Issue by Munter** [netlify/build-image#173]
For build-time web font subsetting (used in https://github.com/Munter/subfont), I'd like https://github.com/fonttools/fonttools to be available in the Netlify build image.

The install command that pulls in what I am using is `pip install fonttools brotli zopfli`, but I am not a regular python user, and know nothing of the complexities of having multiple parallel python versions  and pip and so forth.

I'd be happy to make a PR if someone could give me a pointer on how this could be done in the Dockerfile. The lack of an existing copy/pasteable `pip install` is blocking me right now :)

**Comment by brycekahle** [comment]
@Munter If you include a `requirements.txt` file, we will `pip install` for you. See https://github.com/netlify/build-image/blob/master/run-build-functions.sh#L314-L326

**Comment by Munter** [comment]
That's quite useful and completely solves my problem. Thank you!

I couldn't find this anywhere in the docs. Have I just been a bit too fast to skip over that part?

**Comment by shansmith01** [comment]
@Munter Any chance you can share the requirements.txt file you used to get this working in the end?

**Comment by Munter** [comment]
@shansmith01 Sure. My setup is the simplest possible use of `requirements.txt`. No version locks or anything:

```
fonttools
brotli
zopfli
```

https://github.com/Munter/mntr.dk/blob/subfont/requirements.txt

**Comment by shansmith01** [comment]
Wow. Easy as. Thanks for sharing
