### ISSUE TITLE
out of date packages / old version of Ubuntu

### ISSUE THREAD

**Issue by slang800** [netlify/build-image#189]
The build image comes with:

- `make` version `3.81`, which was released in 2006. The current version that Ubuntu is [shipping](https://packages.ubuntu.com/bionic/make) with is `4.1`
- `jq` version `1.3`, which was released in 2015. The current version that Ubuntu is [shipping](https://packages.ubuntu.com/bionic/jq) with is `1.5`

This is because the image is built on Ubuntu 14.04, which is nearing it's EOL. Can we upgrade to the latest Ubuntu base image?

**Comment by bcomnes** [comment]
Agreed! See https://github.com/netlify/build-image/issues/254 
A user serviceable setting is coming soon.
