### ISSUE TITLE
can't run any command due to nvm error

### ISSUE THREAD

**Issue by lnhrdt** [netlify/build-image#19]
My node netlify build is hanging so I thought I'd try to run it in the docker image:

```
buildbot@b8dca7eb5755:/$ build npm install
/usr/local/bin/build: line 33: /.nvm/nvm.sh: No such file or directory
```

and trying something simpler:

```
buildbot@b8dca7eb5755:/$ build echo hai
/usr/local/bin/build: line 33: /.nvm/nvm.sh: No such file or directory
```

Any ideas what's going on?

**Comment by rybit** [comment]
The issue is that the .nvm is in the home directory. We run `source $HOME/.nvm/nvm.sh` and that should set this up right.

**Comment by lnhrdt** [comment]
I've tried your suggestion but am getting the same result. Am I missing something?

```
buildbot@d9a259ade3b2:/$ source $HOME/.nvm/nvm.sh
buildbot@d9a259ade3b2:/$ build npm install
/usr/local/bin/build: line 33: /.nvm/nvm.sh: No such file or directory
```

**Comment by rybit** [comment]
I am seeing this: 

```
$ docker run -it netlify/build /bin/bash
buildbot@eec9516f5dc3:/$ source $HOME/.nvm/nvm.sh
buildbot@eec9516f5dc3:/$ nvm --version
0.31.4
buildbot@eec9516f5dc3:/$ build
Usage: /usr/local/bin/build <your build cmd>```

Are you not?

**Comment by fool** [comment]
I saw this too for awhile, but we did get it fixed up.  @lnhrdt can you ping again if you are still seeing it with the latest netlify/build docker image?
