### ISSUE TITLE
Curl and Zip PHP extension missing

### ISSUE THREAD

**Issue by igk1972** [netlify/build-image#194]
I try make a generator of static sites based on Grav. :-)

However, dependencies require the expansions of the curl and zip.
It is not yet in the build image. 
I think that not a few projects also require this.

Adding it could be as simple as sudo apt-get install php7.2-curl php7.2-zip.

Could create a PR as well

**Comment by brycekahle** [comment]
@igk1972 Please make a PR, including php5.6 packages if you could.
