### ISSUE TITLE
Permissions problem inside Docker machine

### ISSUE THREAD

**Issue by gurdotan** [netlify/build-image#2]
Inside a local docker machine, I do `cd /opt/repo` and then run my site's build script (using Grunt: `grunt build`).  But is seems that the first build task, that tries to a temporary folder, fails on insufficient permissions:

```
Warning: Unable to delete "dist" file (EACCES, permission denied 'dist'). Use --force to continue.
```

I see that the user inside the machine is called `buildbot`, and all files in the repo have these permissions:
```
-rwxr-xr-x  1 1000 staff 2533 Jul 30 16:45 Gruntfile.js
```

Any ideas?

**Comment by biilmann** [comment]
Make sure to run the special build command on the build image. So instead
of running `grunt build` you should run `build grunt build`.

This will stimulate the build process on netlify's build machines by
checking out a clone of your repo to ~/repo and installing all dependencies
before running your command.

**Comment by gurdotan** [comment]
Works like a charm, my bad for not sticking to the docs word by word.
