### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by yoursunny** [netlify/build-image#201]
[Doxygen](http://www.doxygen.nl/) is the de facto standard tool for generating documentation from annotated C++ sources.
It should be included in the build image, so that Netlify can be used to publish code documentation from C++ projects.

**Comment by fool** [comment]
I'm not at all familiar with doxygen, but I wonder if you can install it via npm or as a Gem or as a python package?  Many of those types of utilities are, and then we'd be able to automatically install it for you before build (see https://www.netlify.com/docs/build-settings/ for more details).


This is the first request for it that I'm aware of so it seems likely that it is installable via one of the methods above.  I see a node module for it, for instance:  https://www.npmjs.com/package/doxygen

If not, feel free to submit a Pull Request to add it to our build image.

**Comment by yoursunny** [comment]
Doxygen is normally installed from APT:

```
sudo apt-get install doxygen graphviz
```

The `doxygen` NPM package merely downloads a Doxygen binary. But it would not work because the binary depends on `libclang.so.6` that does not exist in a normal Ubuntu system.

**Comment by yoursunny** [comment]
Hey @fool , this request has been open for almost three months. Can you merge the pull request please?
