### ISSUE TITLE
Fails build with the current version of g++

### ISSUE THREAD

**Issue by jwicks31** [netlify/build-image#214]
We are trying to install a package that has a dependency of json-ld, which requires g++ 4.9 or higher.

Branch:
https://github.com/poetapp/explorer-web/tree/netlify-poet-js

Error from the Netlify Deploy Details:
```
node-gyp rebuild
1:14:43 PM: make: Entering directory `/opt/build/repo/node_modules/rdf-canonize/build'
1:14:43 PM:   CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
1:14:44 PM:   CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
1:14:44 PM:   CXX(target) Release/obj.target/urdna2015/lib/native/NQuads.o
1:14:44 PM: ../lib/native/NQuads.cc: In static member function ‘static std::string RdfCanonize::NQuads::serializeQuad(const RdfCanonize::Quad&)’:
1:14:44 PM: ../lib/native/NQuads.cc:72:62: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [3])’
1:14:44 PM:      escaped = regex_replace(escaped, REGEX_BACK_SLASH, "\\\\");
1:14:44 PM:                                                               ^
```

**Comment by bcomnes** [comment]
We are in the process of updating the base image which should bring a newer version of g++ I believe.

**Comment by wzalazar** [comment]
@bcomnes do you have an estimated date?

**Comment by bcomnes** [comment]
No date sorry.  Its high priority though.  Soon™️

**Comment by wzalazar** [comment]
@tpluscode I researched about a possible workaround the last week, but not, I didn't find a workaround. Check the link, I left my research there.

**Comment by tpluscode** [comment]
Can this can be closed? I no longer experience this issue in my builds.
