### ISSUE TITLE
Support dotnet core

### ISSUE THREAD

**Issue by Romanx** [netlify/build-image#231]
I use netlify to host my statically generated https://wyam.io/ blog which I have to build on Appveyor and then push to netlify manually as opposed to using your great build images.

Since wyam.io has just migrated to dotnet core it would be possible to install it as a dotnet global tool and run my static generation using netlify much like hugo and other static site generators.

**Comment by daveaglick** [comment]
Probably related to this PR: https://github.com/netlify/build-image/pull/230

**Comment by jhgoodwin** [comment]
FYI, I talked about a way to make it work, here: https://github.com/netlify/build-image/pull/230

**Comment by MysterDru** [comment]
@Romanx  this is working now with the Xenial build image in netlify. I created a gist with 2 scripts that can be used to get it to work.

https://gist.github.com/MysterDru/c4d1fd5a905c92d0d89d6936b2d7a725

set the build command to be `./build.sh` and set the publish directory to point to the wyam output folder.

**Comment by mraerino** [comment]
seems solved.
