### ISSUE TITLE
Support elixir

### ISSUE THREAD

**Issue by thiamsantos** [netlify/build-image#232]
Would be great if netlify support [elixir](https://elixir-lang.org/) builds. We will be able to use any static site generator available for elixir, host documentation and similar things like coverage report.

**Comment by szTheory** [comment]
It's supported now https://github.com/netlify/build-image/blob/9cade8af58c2cf3a17a1e9433d2e979149488837/Dockerfile#L47

**Comment by lovebes** [comment]
Is this still an issue or resolved? Asking because issue is still open. I'd love to use elixir too :)

**Comment by kitop** [comment]
This is supported now, Elixir 1.9.1 is installed in Focal: https://github.com/netlify/build-image/blob/7f982ee89631b4cd9ccab6cfd948ec9a7fb242cf/Dockerfile#L44

https://github.com/netlify/build-image/blob/focal/included_software.md#languages
