### ISSUE TITLE
/usr/local/bin/run-build-functions.sh: line 334: pip: command not found

### ISSUE THREAD

**Issue by tiangolo** [netlify/build-image#239]
I'm trying to deploy a package docs using the automated CI system, but I'm getting:

```
/usr/local/bin/run-build-functions.sh: line 334: pip: command not found
```

Here's my repo: https://github.com/tiangolo/fastapi

I'm using `pipenv`, so I have a `Pipfile`.

I can see on the logs that the `Pipfile` is being used:

```
8:22:39 AM: Found Pipfile restoring Pipenv virtualenv
8:22:39 AM: Started restoring cached python virtualenv
8:22:39 AM: Finished restoring cached python virtualenv
```

I have `mkdocs` as part of my `dev-dependencies`, I don't know if from there it is then not installed.

When I didn't have a `requirements.txt` file I was getting errors of `mkdocs: command not found`, even though it said that it installed the dependencies from the `Pipfile`.

Then I tried adding a `requirements.txt` file, but now the error is a `pip: command not found`.

I also tried changing the build command to `pipenv run -- mkdocs build`, but then I got `pipenv: command not found` errors.

Am I doing something wrong? Am I missing something?

**Comment by tiangolo** [comment]
After a lot of "trial and error" with the image locally, I found a recipe to make it work.

* I don't have a `requirements.txt` file anymore
* I'm using `pipenv` with a `Pipfile`
* The build image installs only the packages in the `Pipfile` from the `packages` section. And I have `mkdocs` in the `dev-packages` section (installed with `pipenv install --dev mkdocs`).

I added a bash script `netlify-docs.sh` with:

```bash
#!/usr/bin/env bash
pip install pipenv
pipenv install --dev
mkdocs build
```

And my build command now is `bash netlify-docs.sh`.

The script:
* Installs `pipenv` (because the packages are installed from the `Pipfile` but `pipenv` is not actually installed)
* Installs the packages from the `Pipfile` including those in the `dev-packages` section
* Finally, runs `mkdocs`.

---

Should I close this issue or should this recipe be documented somewhere else first?

**Comment by bcomnes** [comment]
I'm working on updating the build image right now and incorporating a smoother pipenv workflow is something we're considering.  Unless there is an a bug, we can close, but this flow will be improved soon.

**Comment by bcomnes** [comment]
Lets close for now.  Let me know if there is more to discuss and we can reopen.
