### ISSUE TITLE
Build-image's Pipenv implementation only support Python 2.7

### ISSUE THREAD

**Issue by mashedkeyboard** [netlify/build-image#240]
Pipenv was requested in #151 and added afterwards, but it's been hardcoded in to only work on Python 2.7 - see https://github.com/netlify/build-image/blob/master/run-build-functions.sh#L22.

Was this done for any particular reason? If not, am happy to make a PR putting it into whatever Python version is requested by the runtime.txt.

**Comment by minhoryang** [comment]
Why don't we just use `.python-version` as pyenv does.

**Comment by bcomnes** [comment]
Thats a good idea, maybe we can support that.

**Comment by bcomnes** [comment]
Just an update, I looked into moving python support to use something like pyenv to suppor any python version, but I found that it requires that you build python from source, which can be very time consuming.  

Does pipenv support downloading and using any python version from a prebuilt binary?

**Comment by jayvdb** [comment]
I tried using a Pipfile which specified python version 3.6, without a runtime.txt, and the Xenial build failed with `/usr/local/bin/run-build-functions.sh: line 339: pip: command not found`

```console
10:11:41 PM: Starting build script
10:11:41 PM: Installing dependencies
10:11:41 PM: Found Pipfile restoring Pipenv virtualenv
10:11:41 PM: Started restoring cached python virtualenv
10:11:41 PM: Finished restoring cached python virtualenv
10:11:43 PM: Downloading and installing node v10.16.3...
10:11:43 PM: Downloading https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz...
10:11:43 PM: 
#########
10:11:43 PM:                     12.8%
10:11:43 PM: 
##########################################################
10:11:43 PM:       80.9%
10:11:43 PM: 
############################################################
10:11:43 PM: ############ 100.0%
10:11:43 PM: Computing checksum with sha256sum
10:11:43 PM: Checksums matched!
10:11:47 PM: Now using node v10.16.3 (npm v6.9.0)
10:11:47 PM: Attempting ruby version 2.6.2, read from environment
10:11:49 PM: Using ruby version 2.6.2
10:11:49 PM: Using PHP version 5.6
10:11:49 PM: Installing pip dependencies
10:11:49 PM: Started restoring cached pip cache
10:11:49 PM: Finished restoring cached pip cache
10:11:49 PM: /usr/local/bin/run-build-functions.sh: line 339: pip: command not found
10:11:49 PM: Error installing pip dependencies
10:11:49 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:11:49 PM: Error running command: Build script returned non-zero exit code: 1
10:11:49 PM: Failing build: Failed to build site
```

When using `runtime.txt` the log would contain

```
xx:xx:xx AM: Python version set to 3.6
```

**Comment by johtso** [comment]
Any updates on this? Or workarounds? This is currently blocking me from upgrading my projects to Python 3.

**Comment by kitop** [comment]
Closing this as it hasn't had any updates in a while. In the focal image, we now support newer python versions and those can be set in a few ways. Docs: https://docs.netlify.com/configure-builds/manage-dependencies/#python
