### ISSUE TITLE
update "included" ruby versions to include new defaults and versions that work with new bundler

### ISSUE THREAD

**Issue by fool** [netlify/build-image#249]
Per #245 we had a sudden update in default ruby version and now have new recommended versions too:

- 2.3.6
- 2.4.5
- (presumably 2.5.3 though no customer has confirmed that yet)
- 2.6.0

Putting those in the image already (rather than having rvm install pull them down) will speed up everyone's builds and save Netlify some bandwidth costs.

**Comment by bcomnes** [comment]
should be done now.
