### ISSUE TITLE
Ubuntu 16.04 Xenial Dev Image Testing

### ISSUE THREAD

**Issue by bcomnes** [netlify/build-image#254]
I am currently developing the next version of the build-image.  Given the growing need to access features provided by the newer image, I'm opening up this issue to accept requests for specific sites to use the new `dev` image in a limited beta period.  If you would like your site moved over to the new `dev` image before we launch features to allow you to self service image selection, please post the site slug in this issue.  I will be tracking which sites have been enabled in the OP.

### What to expect:

- No stability guarantees.   I will be pushing out changes to the image during this beta period.  My aim is to maintain its stability, but it may break or change underneath you.  If you find yourself in a broken state, and don't see any relevant issues related to your issue, please open an issue.
- I will be adding and removing the sites from the dev image beta, but turnaround time or getting added to the beta image isn't guaranteed.
- Specific issues with the dev image should be opened and tracked in separate issues from this one.
- Beta participation is coordinated in this public issue, please consider if this fits your needs.
- If I can't confirm you own the site from your github account, I may need to request more information from you.
- Please consider these constraints before requesting critical sites be moved to this image beta test.
- Thank you for your interest in helping out!

### Sites added to the beta

(Unchecked = request acknowledged; Checked = confirmed and moved to dev image)

- [x] `test-deploy-site-dev` @bcomnes 
- [x] `tecidev` @bwklein
- [x] `romant` @romant
- [x] `eloquent-morse-196fd2` @davidsneighbour
- [ ] `12bit-blog` @nguyenvanduocit
- [x] `kind-bartik-cd167d` @jamescrowley
- [x] `negative-reviews` @StefanoChiodino
- [x] `remoteorigin` @pavelbinar
- [x] `grumpycorp` @rgiese
- [x] `yonson` @y0ns0n
- [x] `aloralabs` @eberkund
- [x]  `kudo-www` @guenter
- [x] `katyweaver` @mikaelsnavy
- [ ] `raaloo-dev` @randallmlough

**Comment by eberkund** [comment]
Please add `aloralabs`, thanks!

**Comment by bcomnes** [comment]
I'll start enabling people once https://github.com/netlify/build-image/pull/244 is built and deployed.

**Comment by bcomnes** [comment]
@nguyenvanduocit: I couldn't locate a site slug `12bit-blog` can you confirm the correct slug?

**Comment by bcomnes** [comment]
@eberkund, @y0ns0n, @rgiese, @pavelbinar, @StefanoChiodino, @jamescrowley, @davidsneighbour, @romant, @bwklein

All of those sites are now on the dev image.

**Comment by boothead** [comment]
Hi, could you add `commandodev` to this list as well please? Slightly off topic, but you you consider supporting [nixos](https://nixos.org/) or just `nix` packaged sites?

**Comment by eberkund** [comment]
After deploying with the new image everything is working smoothly on my site, great work!

**Comment by bcomnes** [comment]
@eberkund Glad to hear it!

**Comment by bcomnes** [comment]
@boothead

In the short term, we focusing on building out the ubuntu xenial image as the successor to the 14.04 image.  Down the road we hope to increase the amount of flexibility our CI system offers in terms of packages and images. 

In terms of `commandodev`, possibly, but I don't have an answer at the moment.

**Comment by randallmlough** [comment]
@bcomnes I would gladly test on an account level if that's possible. All existing and new sites on our account need the latest Hugo version.

**Comment by bcomnes** [comment]
@randallmlough Sure! Which account?

**Comment by 007** [comment]
Why 16.04 instead of 18.04? Why start 3 years behind the curve?

**Comment by bcomnes** [comment]
@007 we will be doing a 18.04 once we complete the 16.04.  We had to implement a number of infrastructural changes to accommodate additional images and we are just getting to revamping our build images.

**Comment by otake84** [comment]
Please add `otake84`, thanks!

**Comment by randallmlough** [comment]
@bcomnes raaloo-dev is the account name

**Comment by mikaelsnavy** [comment]
Please add `katyweaver`! Thanks! :+1:

**Comment by IsmailM** [comment]
Hey @bcomnes, Just wondering if there are any timelines for this to be made live?

**Comment by bcomnes** [comment]
@IsmailM We are among for next week.  I'll add anyone not added yet who wants it today.  Once we go live, you will have the ability to switch between images on your own.

**Comment by guenter** [comment]
@bcomnes please add `kudo-www`. Thanks!

**Comment by bcomnes** [comment]
Added:

- `kudo-www`
- `katyweaver`

Account level:

- `raaloo-dev` - Will be able to turn that on next week.

**Comment by bcomnes** [comment]
This is live now!  You should all have access to build image selection in your site settings now.  Thank you for all of your help!
