### ISSUE TITLE
Add Rust to build-image

### ISSUE THREAD

**Issue by nolessafool** [netlify/build-image#293]
For using, you know, during builds.

Requested by Pro customer here in our helpdesk.  Others should +1 if they want this too!

- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/21364638638

**Comment by bcomnes** [comment]
Sounds good! No time now, but so a community PR could land this sooner than later.

**Comment by yacoob** [comment]
FWIW, I've just opened https://github.com/netlify/build-image/pull/320 .

**Comment by ultrasaurus** [comment]
Looks like there was a community PR, but it languished for lack of attention.  Does Netlify plan to support Rust?
