### ISSUE TITLE
Move to Go 1.12

### ISSUE THREAD

**Issue by lucacasonato** [netlify/build-image#294]
We are currently still on 1.10 although a newer version has been out for the last 6 months. We should scrap #206 and update to go 1.12 right away. Maybe have a GO_VERSION env var like for Node and Ruby. A lot of projects rely on `go mod` which cant be used in versions under 1.11.

**Comment by bcomnes** [comment]
You should be able to access go 1.12 by setting the env var GO_VERSION to 1.12 in the xenial image. There is a bug with go module caching we are trying to fix, but builds should still work.

**Comment by lucacasonato** [comment]
Ah okay. I couldn't find documentation for GO_VERSION on netlify.com/docs.

**Comment by nolessafool** [comment]
Yup, it's here instead :)  

- https://github.com/netlify/build-image/blob/xenial/included_software.md
- https://github.com/netlify/build-image/blob/trusty/included_software.md

We're reviewing those defaults now - may not be perfectly accurate and won't necessarily reflect older sites that were setup awhile ago.

**Comment by bcomnes** [comment]
To add more context, we don't want to upgrade software on existing sites automatically.  When you create a site, we pin the versions of everything that isn't specified with an ENV var.  In the future, I hope to expose this in a more obvious manner.  With respect to documentation, noted!  I will try to improve that on the next pass.

Closing for now, please let me know if there are any remaining issues that need discussion.
