### ISSUE TITLE
Hugo downloads moved to github.com/gohugoio/hugo instead of spf13/hugo causing failing builds.

### ISSUE THREAD

**Issue by overlordofmu** [netlify/build-image#311]
### Issue

The downloadable binary version of Hugo on GitHub has moved from spf13/hugo to gohugoio/hugo causing downloads of the Hugo binary to fail.

### How to Reproduce

To reproduce set the environment variable `HUGO_VERSION`  to the value `0.54` in the Netlify deploy settings (or in the `netlify.toml` file). Then trigger a new build and clear cache when triggering.

There will be an error like so:

```
12:15:20 AM: Installing Hugo 0.54
12:15:21 AM: Error during Hugo 0.54 install: error downloading project spf13/hugo, from https://github.com/spf13/hugo/releases/download/v0.54/hugo_0.54_Linux-64bit.tar.gz - binary doesn't seem to exist: 404
12:15:21 AM: Error running command: Build script returned non-zero exit code: 1
12:15:21 AM: Failing build: Failed to build site
12:15:21 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
```

This is because the correct download link would be:

```
https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
```

Note, if the Hugo version is 0.53 or older this doesn't occur. Only versions 0.54 and newer are affected.

**Comment by nolessafool** [comment]
@overlordofmu this is because they changed the version format after 0.53.  Nothing to do with the redirect from spf13->gohugoio which has worked well for a year now :)

It went from `0.53` to 0.54.0` .  Closing

**Comment by bcomnes** [comment]
Ah yeah, dang.  We may be able to accommodate that in upstream bin-rc templates.
