### ISSUE TITLE
Using Submodules

### ISSUE THREAD

**Issue by hmnd** [netlify/build-image#316]
How would I go about cloning all the submodules in my project on build? It appears that you only do a `git clone`, so I'd either like to run `git submodule update --recursive --remote` in my build command (doesn't work for me) or somehow add `--recursive-submodules` to the initial clone.

**Comment by rybit** [comment]
Please write into support@netlify.com so that they can help with your particular site and give guidance

**Comment by overlordofmu** [comment]
@hmnd, I'm part of the Netlify support team and I'm looking into a feature request which will address both this and the concept of "shallow cloning" here:

https://github.com/netlify/build-image/issues/317

And please do email support if you would like to discuss this in more detail (as this issue is closed for now).

**Comment by hmnd** [comment]
@overlordofmu I actually did email support prior to discovering this repo. I'm glad you're already looking into it! :) Would you mind emailing me or taking on my ticket perhaps to discuss? Particularly interested if you know of some work around to this in the interim.

**Comment by camilodelvasto** [comment]
We also need this badly... also interested in a workaround if there is any way of doing it... thanks!

**Comment by nolessafool** [comment]
@hmnd your assertion is incorrect.   This is how we clone your repo:

`git clone git@...`
and then we cd to the repo and run:
`git submodule update -f --init`

This happens every time we clone and you cannot prevent it :)

I'm not a git expert so not quite sure if there is a meaningful difference in the --recursive option - is that "look for submodules WITHIN your submodules?"

**Comment by gesellix** [comment]
This one worked for me, after a usual `git clone git@...`:

```git submodule update -f --init --recursive```

Example output without `--recursive`:

```
λ git submodule update --force --init
Submodule 'site/themes/docsy' (https://github.com/google/docsy.git) registered for path 'site/themes/docsy'
Cloning into '.../site/themes/docsy'...
Submodule path 'site/themes/docsy': checked out 'fd36c715b54218c404f607c354b04695435c1882'
```

Example output with `--recursive`:

```
λ git submodule update --force --init --recursive
Submodule 'site/themes/docsy' (https://github.com/google/docsy.git) registered for path 'site/themes/docsy'
Cloning into '.../site/themes/docsy'...
Submodule path 'site/themes/docsy': checked out 'fd36c715b54218c404f607c354b04695435c1882'
Submodule 'assets/vendor/Font-Awesome' (https://github.com/FortAwesome/Font-Awesome.git) registered for path 'site/themes/docsy/assets/vendor/Font-Awesome'
Submodule 'assets/vendor/bootstrap' (https://github.com/twbs/bootstrap.git) registered for path 'site/themes/docsy/assets/vendor/bootstrap'
Cloning into '.../site/themes/docsy/assets/vendor/Font-Awesome'...
Cloning into '.../site/themes/docsy/assets/vendor/bootstrap'...
Submodule path 'site/themes/docsy/assets/vendor/Font-Awesome': checked out '9339b98d888ddcf12d914ece0f4a236a0378577d'
Submodule path 'site/themes/docsy/assets/vendor/bootstrap': checked out '3b558734382ce58b51e5fc676453bfd53bba9201'
```
