### ISSUE TITLE
Caching no longer works

### ISSUE THREAD

**Issue by yacoob** [netlify/build-image#318]
I'm probably missing something here :)

I took a stab at adding Rust support to the build image. Things seem to be working fine, except my cache (as in, `$NETLIFY_CACHE_DIR`) is not getting populated. It looks like since 23b55c2959ea7a2b87742e7da7812514fb386bd0 `cache_artifacts` is not getting called at all during `run-build.sh`. As a result, no caching is performed and every build starts from scratch. Adding `cache_artifacts` as a last step before exiting from `run-build.sh` results in cache getting populated.

Now, the confusing bit is the fact that my actual deploys on netlify say:

```
10:44:16 PM: build-image tag: v3.3.2
```

but then continue to say:

```
10:44:47 PM: Caching artifacts
```

3.3.2 should have caching broken. I'm *obviously* missing something here, right? :D 

Thanks!

**Comment by yacoob** [comment]
For reference: this is what I arrived at:
https://github.com/netlify/build-image/compare/xenial...yacoob:rust?expand=1

The caching wouldn't work in local tests, until I've added that explicit call to `cache_artifacts`.

**Comment by XhmikosR** [comment]
This is definitely a regression in the Xenial image. Can we get a fix please?
