### ISSUE TITLE
Bundler Version warning with no fix in sight

### ISSUE THREAD

**Issue by vphilot** [netlify/build-image#331]
Can't finish build due to Bundle version -- follower instructions with no success, log below:

7:12:09 PM: Build ready to start
7:12:12 PM: build-image version: 8e315e54bc4032a32e73290be556cde4f8348c12
7:12:12 PM: build-image tag: v2.8.2
7:12:12 PM: buildbot version: b925d11411cabfe7b120501027bd0e96dbc28dde
7:12:13 PM: Fetching cached dependencies
7:12:13 PM: Starting to download cache of 302.7MB
7:12:18 PM: Finished downloading cache in 5.188965822s
7:12:18 PM: Starting to extract cache
7:12:22 PM: Finished extracting cache in 4.650002988s
7:12:23 PM: Finished fetching cache in 10.17806011s
7:12:23 PM: Starting to prepare the repo for build
7:12:23 PM: Preparing Git Reference refs/heads/master
7:12:33 PM: Starting build script
7:12:33 PM: Installing dependencies
7:12:35 PM: Downloading and installing node v10.16.3...
7:12:35 PM: Downloading https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz...
7:12:35 PM: 
#################
7:12:35 PM:                                    24.0%
7:12:35 PM: 
##################################################################
7:12:35 PM:  91.9%
7:12:35 PM: #
7:12:35 PM: #########################################
7:12:35 PM: ############################## 100.0%
7:12:35 PM: Computing checksum with sha256sum
7:12:35 PM: Checksums matched!
7:12:39 PM: Now using node v10.16.3 (npm v6.9.0)
7:12:39 PM: Attempting ruby version 2.6.2, read from environment
7:12:41 PM: Using ruby version 2.6.2
7:12:41 PM: Using PHP version 5.6
7:12:41 PM: Started restoring cached ruby gems
7:12:41 PM: Finished restoring cached ruby gems
7:12:41 PM: Installing gem bundle
7:12:42 PM: Warning: the running version of Bundler (2.0.1) is older than the version that created the lockfile (2.0.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
7:12:45 PM: Fetching gem metadata from https://rubygems.org/
7:12:45 PM: .
7:12:46 PM: .
7:12:46 PM: .
7:12:46 PM: .
7:12:46 PM: .
7:12:46 PM: .
7:12:47 PM: .
7:12:47 PM: .
7:12:47 PM: .
7:12:47 PM: .
7:12:47 PM: .
7:12:47 PM: Fetching public_suffix 3.1.1
7:12:47 PM: Installing public_suffix 3.1.1
7:12:48 PM: Fetching addressable 2.6.0
7:12:48 PM: Installing addressable 2.6.0
7:12:49 PM: Using bundler 2.0.1
7:12:49 PM: Fetching colorator 1.1.0
7:12:49 PM: Installing colorator 1.1.0
7:12:49 PM: Fetching concurrent-ruby 1.1.5
7:12:49 PM: Installing concurrent-ruby 1.1.5
7:12:49 PM: Fetching eventmachine 1.2.7
7:12:49 PM: Installing eventmachine 1.2.7 with native extensions
7:13:13 PM: Fetching http_parser.rb 0.6.0
7:13:13 PM: Installing http_parser.rb 0.6.0 with native extensions
7:13:15 PM: Fetching em-websocket 0.5.1
7:13:15 PM: Installing em-websocket 0.5.1
7:13:15 PM: Fetching ffi 1.11.1
7:13:16 PM: Installing ffi 1.11.1 with native extensions
7:13:27 PM: Fetching forwardable-extended 2.6.0
7:13:27 PM: Installing forwardable-extended 2.6.0
7:13:28 PM: Fetching i18n 0.9.5
7:13:28 PM: Installing i18n 0.9.5
7:13:28 PM: Fetching rb-fsevent 0.10.3
7:13:28 PM: Installing rb-fsevent 0.10.3
7:13:28 PM: Fetching rb-inotify 0.10.0
7:13:28 PM: Installing rb-inotify 0.10.0
7:13:28 PM: Fetching sass-listen 4.0.0
7:13:28 PM: Installing sass-listen 4.0.0
7:13:28 PM: Fetching sass 3.7.4
7:13:28 PM: Installing sass 3.7.4
7:13:29 PM: Fetching jekyll-sass-converter 1.5.2
7:13:29 PM: Installing jekyll-sass-converter 1.5.2
7:13:29 PM: Fetching ruby_dep 1.5.0
7:13:29 PM: Installing ruby_dep 1.5.0
7:13:29 PM: Fetching listen 3.1.5
7:13:29 PM: Installing listen 3.1.5
7:13:29 PM: Fetching jekyll-watch 2.2.1
7:13:29 PM: Installing jekyll-watch 2.2.1
7:13:29 PM: Fetching kramdown 1.17.0
7:13:29 PM: Installing kramdown 1.17.0
7:13:30 PM: Fetching liquid 4.0.3
7:13:30 PM: Installing liquid 4.0.3
7:13:30 PM: Fetching mercenary 0.3.6
7:13:30 PM: Installing mercenary 0.3.6
7:13:30 PM: Fetching pathutil 0.16.2
7:13:30 PM: Installing pathutil 0.16.2
7:13:30 PM: Fetching rouge 3.9.0
7:13:30 PM: Installing rouge 3.9.0
7:13:31 PM: Fetching safe_yaml 1.0.5
7:13:31 PM: Installing safe_yaml 1.0.5
7:13:31 PM: Fetching jekyll 3.8.6
7:13:31 PM: Installing jekyll 3.8.6
7:13:31 PM: Bundle complete! 1 Gemfile dependency, 26 gems now installed.
7:13:31 PM: Bundled gems are installed into `/opt/build/cache/bundle`
7:13:31 PM: Post-install message from sass:
7:13:31 PM: Ruby Sass has reached end-of-life and should no longer be used.
7:13:31 PM: * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
7:13:31 PM:   primary implementation: https://sass-lang.com/install
7:13:31 PM: * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
7:13:31 PM:   sassc gem: https://github.com/sass/sassc-ruby#readme
7:13:31 PM: * For more details, please refer to the Sass blog:
7:13:31 PM:   https://sass-lang.com/blog/posts/7828841
7:13:31 PM: Gem bundle installed
7:13:31 PM: Started restoring cached node modules
7:13:31 PM: Finished restoring cached node modules
7:13:32 PM: Installing NPM modules using NPM version 6.9.0
7:13:47 PM: > gifsicle@4.0.1 postinstall /opt/build/repo/node_modules/gifsicle
7:13:47 PM: > node lib/install.js
7:13:47 PM:   ✔ gifsicle pre-build test passed successfully
7:13:47 PM: > jpegtran-bin@4.0.0 postinstall /opt/build/repo/node_modules/jpegtran-bin
7:13:47 PM: > node lib/install.js
7:13:48 PM:   ✔ jpegtran pre-build test passed successfully
7:13:48 PM: > optipng-bin@5.1.0 postinstall /opt/build/repo/node_modules/optipng-bin
7:13:48 PM: > node lib/install.js
7:13:48 PM:   ✔ optipng pre-build test passed successfully
7:13:48 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
7:13:48 PM: > node lib/install.js
7:13:49 PM:   ✔ pngquant pre-build test passed successfully
7:13:50 PM: npm
7:13:50 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
7:13:50 PM: npm WARN notsup
7:13:50 PM:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:13:50 PM: added 749 packages from 338 contributors and audited 12287 packages in 16.777s
7:13:50 PM: found 0 vulnerabilities
7:13:50 PM: NPM modules installed
7:13:50 PM: Started restoring cached go cache
7:13:50 PM: Finished restoring cached go cache
7:13:50 PM: unset GOOS;
7:13:50 PM: unset GOARCH;
7:13:50 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
7:13:50 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
7:13:50 PM: go version >&2;
7:13:50 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
7:13:50 PM: go version go1.12 linux/amd64
7:13:50 PM: Installing missing commands
7:13:50 PM: Verify run directory
7:13:50 PM: Executing user command: jekyll build
7:13:50 PM: Activating bundler (2.0.2) failed:
7:13:50 PM: Could not find 'bundler' (2.0.2) required by your /opt/build/repo/Gemfile.lock.
7:13:50 PM: To update to the latest version installed on your system, run `bundle update --bundler`.
7:13:50 PM: To install the missing version, run `gem install bundler:2.0.2`
7:13:50 PM: Checked in 'GEM_PATH=/opt/buildhome/.rvm/gems/ruby-2.6.2:/opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0', execute `gem env` for more information
7:13:50 PM: To install the version of bundler this project requires, run `gem install bundler -v '2.0.2'`
7:13:50 PM: Skipping functions preparation step: no functions directory set
7:13:50 PM: Caching artifacts
7:13:50 PM: Started saving ruby gems
7:13:50 PM: Finished saving ruby gems
7:13:50 PM: Started saving node modules
7:13:50 PM: Finished saving node modules
7:13:50 PM: Started saving pip cache
7:13:50 PM: Finished saving pip cache
7:13:50 PM: Started saving emacs cask dependencies
7:13:50 PM: Finished saving emacs cask dependencies
7:13:50 PM: Started saving maven dependencies
7:13:50 PM: Finished saving maven dependencies
7:13:50 PM: Started saving boot dependencies
7:13:50 PM: Finished saving boot dependencies
7:13:50 PM: Started saving go dependencies
7:13:50 PM: Finished saving go dependencies
7:13:53 PM: Error running command: Build script returned non-zero exit code: 42
7:13:53 PM: Failing build: Failed to build site
7:13:53 PM: failed during stage 'building site': Build script returned non-zero exit code: 42
7:13:53 PM: Finished processing build request in 1m41.108372248s

**Comment by nolessafool** [comment]
Bundler v 2.0.1 will work, @vphilot .  This issue:

https://github.com/netlify/build-image/issues/296

...is tracking the lack of flexibility there, so we'll close this as a duplicate
