### ISSUE TITLE
Hey folks, sorry for the delay.  I was out for holidays and a handoff wasn't possible.

### ISSUE THREAD

**Issue by MrsTaylor14** [netlify/build-image#333]
Hey folks, sorry for the delay.  I was out for holidays and a handoff wasn't possible.  

I deployed https://github.com/netlify/build-image/pull/197 yesterday, but determined it wasn't a reliable enough fix.  I partially reverted it here: https://github.com/netlify/build-image/pull/248

I kept the required libraries though, which means if you provide your own hugo extended binary in the build, or download it on build, you can use it by doing something like:

```console
LD_LIBRARY_PATH=$HOME/stdc++6/usr/lib/x86_64-linux-gnu ./hugo
```

The good news is, I've started a deployment of the `dev` branch which is running ubuntu 16 and supports hugo extended by default.  Once that's ready for testing, I will set all of the requested site slugs to use that image instead.  Soon after, we'll make switching between the `precise` image and the `dev` image user serviceable in the site settings. 

Disclaimer: the preview dev image isn't 100%, things will change potentially until we come up with a stability contract on the new xenial image.

Stay posted on this issue for updates, and thank you for your patients on this issue.  It is my primary priority as of now.

_Originally posted by @bcomnes in https://github.com/netlify/build-image/issues/182#issuecomment-452526089_

**Comment by nolessafool** [comment]
I think you unintentionally opened this issue, @MrsTaylor14 so I'll close it.  Please feel free to reopen with a better explanation of what trouble you're having if I was wrong!
