### ISSUE TITLE
Make each (currently) automatic step of our build optional

### ISSUE THREAD

**Issue by depadiernos** [netlify/build-image#335]
As a user, I want to be able to streamline my build pipeline. This isn't easy with the current build-image as a lot of the steps are hardcoded. For instance, even if I will not be using Ruby to build a particular site but have a Gemfile, there is no way to skip installing those dependencies.

Ideally, a way to 'flip' each build step on or off would make help alleviate this issue.<br><br><i>(related to <a href='https://netlify.zendesk.com/agent/tickets/8419'>Zendesk ticket #8419</a>)<br>gz#8419</i>

**Comment by shayonj** [comment]
Hi @depadiernos! Thanks for opening the issue. Agreed, it would be nice to have the 'flip' option. Its something we have been discussing also in https://github.com/netlify/build-image/issues/141. Closing this one for now to ensure all discussions happen at a single place. Feel free to add anything else in the new issue. And/or re-open if you feel the two issues aren't the same.

**Comment by nolessafool** [comment]
ah, thanks @shayonj  - I looked for 10 minutes yesterday and couldn't find that issue :|

**Comment by leonardofaria** [comment]
More info (it was my ticket):
I have a style guide created using Hologram (Ruby) and Storybook (JS). There is no need to have PHP or Go in my builds.
