### ISSUE TITLE
Ruby version is not current with production build-image

### ISSUE THREAD

**Issue by motleydev** [netlify/build-image#340]
This image says to set the ruby version to one of `2.4.3 2.2.9 2.3.6`

The live build tool says that the installed version is 2.6.2

**Comment by verythorough** [comment]
If I understand correctly, you're talking about what's being fixed in this PR: https://github.com/netlify/build-image/pull/337. Is that right?

If not, could you clarify what you mean by "this image" and "the live build tool"? Also, which build image are you using (xenial or trusty)?

**Comment by motleydev** [comment]
Hi @verythorough yes! That is correct! Sorry for the confusion!

**Comment by verythorough** [comment]
No worries! It served as a good reminder to get #337 merged! 😁
