### ISSUE TITLE
xenial image selects Ruby 2.3.6 by default

### ISSUE THREAD

**Issue by abitrolly** [netlify/build-image#342]
In the build https://app.netlify.com/sites/115/deploys/5da4b30f4f49ca0008636b0b

![image](https://user-images.githubusercontent.com/8781107/66772975-9ad38700-eec6-11e9-99ad-335d6ad121da.png)

I double checked documented [environment variables](https://www.netlify.com/docs/continuous-deployment/#build-environment-variables) - there is no `netlify.toml`, no variables in [site settings](https://app.netlify.com/sites/115/settings/deploys#environment) and no support for team settings on my plan.

**Comment by verythorough** [comment]
Ah, it looks like that site was created some time ago. Netlify pins the Ruby version on site creation so you don't have any unexpected changes when the build-image default updates. You can override the pinning by using either of the setting methods you linked above. :)

**Comment by abitrolly** [comment]
I'd better reset all settings somehow without recreating to avoid losing history. Is that possible to do? I don't want to think about other surprises that may lurk from that initial site creation. :D

**Comment by verythorough** [comment]
I think the pinning will be reset if you re-connect your repo (under **Settings > Build & deploy > Continuous deployment > Build settings**). Of course, that just means everything will be re-pinned to the current defaults.

And to be clear, the pinning is there to _avoid_ surprises. Without pinning, updates to the build image would causes change in your build, which is something we always want to avoid. You can read about how we handle dependencies here: https://docs.netlify.com/configure-builds/manage-dependencies/

**Comment by abitrolly** [comment]
If I reconnect, will all previous builds and logs gone for this repo?

**Comment by verythorough** [comment]
No, all previous deploy logs will still be there.

**Comment by verythorough** [comment]
Closing because this seems to be working as expected. Feel free to re-open if there's something I missed!

**Comment by abitrolly** [comment]
To be user friendly, the Netlify could warn if configuration drifted, hidden settings are in effect and differ from defaults.
