### ISSUE TITLE
Trigger build for a specific path

### ISSUE THREAD

**Issue by labkode** [netlify/build-image#345]
I have Netlify integrated with my repo that also contains code and the docs live under a docs/ folder.
However, for any code change not related with the documentation a Netlify build will be triggered, is there a way to tell Netlify to only trigger a build if a file has changed under a certain subfolder?

**Comment by mraerino** [comment]
Hi! Yes there is a way:
https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
Warning: The example command will also ignore the build if the change was in another commit than `HEAD`. You may need to change it accordingly.

You might have to relink your repository for this to take effect.
If you always want to just build a subfolder you can also use the `base` option:
https://docs.netlify.com/configure-builds/common-configurations/#monorepos
This will check for changes in the `base` directory against the cache for last build which check be more useful than the example ignore command.

Next time, for questions like this we'd love to help you in our Community: https://community.netlify.com

**Comment by anthonyquizon** [comment]
How do you set the `base` option when running build-image in a local docker instance?
