### ISSUE TITLE
Failure building netlify preview with python

### ISSUE THREAD

**Issue by cicdw** [netlify/build-image#352]
We use Netlify to build our documentation at https://github.com/PrefectHQ/prefect and [as of today](https://github.com/PrefectHQ/prefect/pull/1791) we are noticing build failures in which Python seems to not be present in the netlify build image.  Here is the full log output of a recent job:

```
7:14:05 PM: Build ready to start
7:14:07 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
7:14:07 PM: build-image tag: v3.3.5
7:14:07 PM: buildbot version: eb060c4dc3a8a73f9004f460f04632708166ca51
7:14:07 PM: Fetching cached dependencies
7:14:07 PM: Starting to download cache of 777.2MB
7:14:11 PM: Finished downloading cache in 4.198721422s
7:14:11 PM: Starting to extract cache
7:14:26 PM: Finished extracting cache in 14.791855748s
7:14:26 PM: Finished fetching cache in 19.226270565s
7:14:26 PM: Starting to prepare the repo for build
7:14:26 PM: Preparing Git Reference pull/1791/head
7:14:29 PM: Found Netlify configuration file. Overriding site configuration
7:14:29 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'docs/.vuepress/dist' versus 'docs/build' in the Netlify UI
7:14:29 PM: Starting build script
7:14:29 PM: Installing dependencies
7:14:29 PM: /usr/local/bin/run-build-functions.sh: line 170: /opt/buildhome/python3.6/bin/activate: No such file or directory
7:14:29 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
7:14:29 PM: Error setting python version from runtime.txt
7:14:29 PM: Please see https://github.com/netlify/build-image/#included-software for current versions
7:14:29 PM: Error running command: Build script returned non-zero exit code: 1
7:14:29 PM: Failing build: Failed to build site
7:14:29 PM: Shutting down logging, 1 messages pending
```

We haven't touched our netlify settings in months, so I'm not sure what would cause this.

The following files are probably relevant:
- [our netlify config](https://github.com/PrefectHQ/prefect/blob/master/netlify.toml)
- [our runtime.txt](https://github.com/PrefectHQ/prefect/blob/master/runtime.txt)

**Comment by rnorth** [comment]
We also have the same issue for https://github.com/testcontainers/testcontainers-java, also for Python 3.6.

**Comment by rnorth** [comment]
Based on deploy logs it looks like:

* our last successful deploy, yesterday, used build image v2.8.2
* since then, failing deploys have tried to use v3.3.5

There was no action on our part to change the build image.

The [Dockerfile](https://github.com/netlify/build-image/blob/xenial/Dockerfile) specifies `python3` and `python3.7` but does not explicitly install `python3.6`.

**Comment by rnorth** [comment]
FWIW, switching to Python 3.7 has fixed the issue for us.

**Comment by mraerino** [comment]
Thank you for figuring this out. This issue seems solved now?

This behaviour is also consistent with our docs at https://github.com/netlify/build-image/blob/xenial/included_software.md#languages

**Comment by cicdw** [comment]
Changing to 3.7 fixed it for us - thanks everyone!

**Comment by mraerino** [comment]
hey, we just noticed that this change should actually not have happened.
you all seem to be on our deprecated build image (ubuntu 14.04) which did include python 3.6

we might be deciding to rollback our change which removed 3.6

if you want to make sure your 3.7 builds keep running I recommend upgrading to the xenial image: https://docs.netlify.com/configure-builds/get-started/#build-image-selection

**Comment by mraerino** [comment]
the change that caused the version jump in your builds and python 3.6 to be missing was rolled back just now. this was only affecting sites on the *old* build image

Please consider moving to the newer build image in any case, if 3.7 works for you.
You can find the switch in your build settings.
