### ISSUE TITLE
~/.cache is not only the pip cache

### ISSUE THREAD

**Issue by frangio** [netlify/build-image#353]
The `~/.cache` directory is treated as the pip cache, but it's actually more than that. It's the default value for `$XDG_CACHE_HOME` according to the XDG Base Directory specification, so there are probably many more tools that use this directory. In fact, yarn places its cache in this directory by default, for example.

The current build script always stores it in the cache, but it only restores it if there is a `requirements.txt` file found, so if the project is understood to be a Python project.

I think it's a great idea to cache this directory but it should also always be restored, and the logs should be changed to reflect that it's more than the pip cache.

https://github.com/netlify/build-image/blob/9cade8af58c2cf3a17a1e9433d2e979149488837/run-build-functions.sh#L621
https://github.com/netlify/build-image/blob/9cade8af58c2cf3a17a1e9433d2e979149488837/run-build-functions.sh#L364

**Comment by duckinator** [comment]
I'm not sure how I feel about keeping all of `~/.cache`, but I think Netlify should do one of:

1. keep the entirety of `~/.cache` and always restore it, or
2. keep `~/.cache/pip`, not `~/.cache`, for pip-related things.

Doing 1 and claiming it's 2 is a potential source of confusion. :slightly_smiling_face:

**Comment by ehmicky** [comment]
Thanks for reporting this issue!
Fixed in #430.
