### ISSUE TITLE
yarn: not found and npm: not found

### ISSUE THREAD

**Issue by roballsopp** [netlify/build-image#358]
I'm newish to docker, so forgive me if I'm doing something dumb here. I'm trying to debug a build issue using a docker file with the netlify/build:xenial image and running into the following errors when building a docker image with my app in it
```
/bin/sh: 1: npm: not found
```
and when I try using yarn
```
/bin/sh: 1: yarn: not found
```
My docker file is:
```
FROM netlify/build:xenial

WORKDIR /usr/app/

COPY . ./

RUN npm install

CMD npm run test
```
I get those errors when running `docker build . -t myImage` or using docker-compose. I've also tried passing the following env vars: with no luck:
```
NODE_VERSION: 12
NODE_ENV: development
NPM_VERSION: 6.10
YARN_VERSION: 1.21.1
```
Any ideas?

**Comment by kitop** [comment]
Closing this as it depends on the Xenial image and it is going to be deprecated: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
We're unlikely to investigate this. If it happens against focal, please re-open and provide an updated description.
