### ISSUE TITLE
Parcel bundler v2 fails to run on trusty and xenial

### ISSUE THREAD

**Issue by jfalxa** [netlify/build-image#361]
I'm using [parcel v2](/parcel-bundler/parcel) to bundle my app however, because of missing dependencies in [parcel watcher](/parcel-bundler/watcher), it fails to run on both build images:

#### Xenial
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/build/repo/node_modules/@parcel/watcher/build/Release/watcher.node)
```

#### Trusty
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.23' not found (required by /opt/build/repo/node_modules/@parcel/watcher/build/Release/watcher.node)
```

Before any eventual fix, do you think a workaround is possible ? 
(Note that I tried the previous version of parcel but it's actually broken in my specific use case)

**Comment by meriadec** [comment]
Same issue. Did you finally found a workaround?

**Comment by jfalxa** [comment]
Sadly no, however it looks like the parcel devs are working on a fix on their side: https://github.com/parcel-bundler/watcher/pull/24

Hopefully it'll be merged soon and this issue won't be one anymore.

**Comment by jfalxa** [comment]
Meanwhile you can still remove your build command from netlify, bundle your files locally and commit them to your repo. It's ugly but it works.

**Comment by jfalxa** [comment]
parcel-side PR was closed. For now, the problem is fixed if you use `parcel@nightly` instead of `parcel@next`
