### ISSUE TITLE
Support `PYTHON_VERSION`, for consistency

### ISSUE THREAD

**Issue by duckinator** [netlify/build-image#362]
Of the [included languages](https://github.com/netlify/build-image/blob/xenial/included_software.md#languages) that have multiple versions available (Ruby, Node.js, Python, PHP, Go), only Python can not use a `<language name>_VERSION` environment variable.

It'd be super nice if this was supported, so it can be specified in `netlify.toml` like with the other languages.

**Comment by duckinator** [comment]
I made an attempt at implementing this over at #363.

**Comment by vbrown608** [comment]
Fixed by #363 - thanks again @duckinator !
