### ISSUE TITLE
React app inside lerna monorepo can't find module from shared packages

### ISSUE THREAD

**Issue by cabezonidas** [netlify/build-image#367]
I have a create-react-app that imports components from other react packages.
My understanding is that yarn uses symlinks for node_modules folder, and works fine locally.
When it deploys, the build fails, saying that my components can't find the modules from the packages of my repo.

What's the best way to build js dependencies? All of those packages are with TS, so they need to be compiled.

Thanks

**Comment by epicfaace** [comment]
Same issue for me -- see https://app.netlify.com/sites/rjsf/deploys/5e684c53d7471d0008f3fbcc

**Comment by epicfaace** [comment]
Never mind, my issue seems to be an issue with my own code, not a Netlify issue.

**Comment by cabezonidas** [comment]
I don't know exactly why, most of my root dependencies were dev dependencies, including lerna js, necessary for bootstrapping all the packages.

Turning devDependencies into dependencies in my package.json solved my issue.

Other hosting providers also fail with dev dependencies for monorepos.
