### ISSUE TITLE
My Gatsby build doesn't work on Netlify

### ISSUE THREAD

**Issue by Pet3ris** [netlify/build-image#377]
Hi There,

I raised an issue at the Gatsby repository but it seems like it's not a Gatsby issue per say: https://github.com/gatsbyjs/gatsby/issues/20786.

Effectively I have a local gatsby repo that works well locally but doesn't compile on Netlify.

WIth the following error:

```
4:40:44 PM: success initialize cache - 0.073s
4:40:44 PM: success copy gatsby files - 0.043s
4:40:44 PM: success onPreBootstrap - 0.003s
4:40:44 PM: success createSchemaCustomization - 0.003s
4:40:45 PM: success source and transform nodes - 0.112s
4:40:45 PM: success building schema - 0.344s
4:40:45 PM: error There was an error in your GraphQL query:
4:40:45 PM: Cannot query field "fields" on type "File".
4:40:45 PM: not finished createPages - 0.032s
4:40:45 PM: Skipping functions preparation step: no functions directory set
```

Could it be an inconsistency of versions or another issue altogether?

**Comment by rybit** [comment]
Hi! I’d recommend opening a support issue with us for help. Or referencing the community pages. This isn’t the best forum to get help in your particular site.
