### ISSUE TITLE
Add support for `helm`

### ISSUE THREAD

**Issue by bangau1** [netlify/build-image#385]
I have curated helm charts in my github repository and need to expose the charts to the public via Netlify.
In order to do this, I need [`helm`](https://helm.sh/) to be included in the build image in netlify so I can generate the helm chart using `helm package` command.

Is it possible to add `helm`?

**Comment by mraerino** [comment]
Helm is available as a Homebrew formula: https://formulae.brew.sh/formula-linux/helm
You might be able to use it once #411 lands.
