### ISSUE TITLE
Once the Netlify Build beta goes GA, remove `zip-it-and-ship-it` code

### ISSUE THREAD

**Issue by ehmicky** [netlify/build-image#386]
With Netlify Build beta, `zip-it-and-ship-it` is now called by `@netlify/build` programmatically from Node.js. Therefore, once we remove the Netlify Build beta feature flag, we will be able to remove the following pieces of code from the buildbot and the `build-image`:
  - [Installing `zip-it-and-ship-it`](https://github.com/netlify/build-image/blob/85f74bd415e22878bad5783a3813dabcb1ffded2/Dockerfile#L360) in the `Dockerfile`
  - Allow configuring the `zip-it-and-ship-it` version (for debugging) with the `ZISI_VERSION`. This undocumented feature is not supported in Netlify Build at the moment. On the other hand, since `zip-it-and-ship-it` is now a moving part inside `@netlify/build`, we can use `NETLIFY_BUILD_CLI_VERSION` to specify the version of `@netlify/build`, therefore the version of `zip-it-and-ship-it` as well.

**Comment by 2color** [comment]
Not sure if this belongs here. But I just discovered defining `ZISI_VERSION` does not properly change the version of `zip-it-and-ship-it` used. 

This is using the normal build image without Netlify Build.

See https://app.netlify.com/sites/netlify-prisma-test/deploys/5e8b03af25d447000671ce08

**Comment by ehmicky** [comment]
@2color You can also upgrade to the latest version of `zip-it-and-ship-it` by opting in [our latest beta](https://docs.netlify.com/configure-builds/build-plugins/).

**Comment by verythorough** [comment]
@ehmicky @Benaiah I'm moving this to the fast-follow milestone. Can you help assign it to the appropriate person?

**Comment by Benaiah** [comment]
@verythorough @ehmicky Sure, I can pick up this issue.
