### ISSUE TITLE
Add support for fgallery

### ISSUE THREAD

**Issue by latiif** [netlify/build-image#396]
#### What is `fgallery`?
`fgallery` is a modern, minimalist javascript photo gallery. [Official website](https://www.thregr.org/~wavexx/software/fgallery/)

It is mainly written in Perl and is available via `apt`/`apt-get` for Debian and it's derivatives in the official repositories. 

#### Is `fgallery` well-established?
I'd say yes. It is available on the Debian/Ubuntu repositories. [`fgallery` on Debian repos](https://packages.debian.org/stretch/fgallery), which IMHO merits `fgallery` a place on the Netlify's build-image.

The package's installed size is less than 1 MB, so the impact on the overall size of the build-image is minimal. 

#### Can't it be downloaded as a stand-alone dependency?
Practical answer: No. `fgallery` is a script that has other dependencies and the most feasible way to get it as stated on the website is from the official repositories. 

I tried building it from source, but it was cumbersome and getting the sources wasn't possible since `sources.list` needs root permissions to update. 

#### We're sold. How can we add `fgallery`?
Glad you asked. It shouldn't be much of a hassle to get this awesome tool, since it's available in Ubuntu's repos. Adding a single `fgallery \` line anywhere in [the `apt-get install` section](https://github.com/netlify/build-image/blob/3a3e63f876b1fa8702f47ede08f4e691d1ba5fbe/Dockerfile#L37#L190) should do the trick.

**Comment by mraerino** [comment]
this seems like a tool which does not qualify as a **generic** build tool. i'm unsure if we'd want to maintain it as a dependency.

people should be able to find photo gallery generators that they can install via a built-in dependency tool, such as `npm`

**Comment by mraerino** [comment]
what about using this package for example?
https://www.npmjs.com/package/fgallery

we can talk about if the required system dependencies are worth to be included

**Comment by nolessafool** [comment]
Advised in community with a good workaround as well:  https://community.netlify.com/t/install-custom-linux-packages-on-deployment-image/12690

I think we can close WONTFIX between those two suggestions;  customer should be able to choose a good workaround :)

**Comment by latiif** [comment]
Good points. Thanks for the pointers.
