### ISSUE TITLE
Testing commands with `&&` fail

### ISSUE THREAD

**Issue by argyleink** [netlify/build-image#4]
The website interface supports the command `grunt fetchJson && grunt compile` but this local Docker instance doesn't. The `run-build.sh` echoes the command, here's a screen shot of me using the build function, and the echo is missing the command following `&&`:

![screen shot 2016-04-27 at 6 48 40 pm](https://cloud.githubusercontent.com/assets/1134620/14873195/ce2e9774-0ca8-11e6-82b8-06699d80a678.png)

Am I doing something wrong? The code in the shell script looks fine, but I'm not very savvy in there.

**Comment by fool** [comment]
Hi there and sorry to respond almost a year late!   You can use the traditional escaping/quoting to get the build command to be parsed correctly no matter what is in it, eg:

```build grunt compile \&\& grunt stylus```

or

```build "grunt complile ; grunt stylus"```
