### ISSUE TITLE
Unable to run bundler command

### ISSUE THREAD

**Issue by abitrolly** [netlify/build-image#40]
Build command `bundle install --without production` fails to run, because Netlify uses its [own variant](https://github.com/netlify/build-image/blob/master/run-build.sh#L42). Build fails, because our `production` setup relies on `pg` gem, which is impossible to skip with Netlify.

**Comment by calavera** [comment]
can you post the error here? is it because the bundler version is too old? we should be able to fix that.

**Comment by abitrolly** [comment]
Full log is in [buildlog.txt](https://github.com/netlify/build-image/files/698295/buildlog.txt). Specific error:
```
1:03:07 AM: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.
```

`gem install pg` should never be executed, because it is only present in `production` section of our Gemfile:
```
group :production do
  gem 'puma', '~> 3.0'
  gem 'pg'
end
```

And all that happens, because Netlify executes `bundler` itself and fails before custom script even has chance to start https://github.com/netlify/build-image/blob/aea09bb3d2360633697bc15671dfd3fa9c6374f6/run-build.sh#L63

**Comment by calavera** [comment]
yes, we run bundler to install dependencies directly before running any build script, that's a behavior that we're not going to change, but we can probably change the the script to take additional flags from an env variable, so you could set something like `BUNDLER_FLAGS="--without production"` in your site settings.

**Comment by abitrolly** [comment]
Either that, or flag that disables automatic ruby step will help.

**Comment by calavera** [comment]
can you give me the name of your site in Netlify, I'd like to look at the problem further.

**Comment by abitrolly** [comment]
yes, it is `hackerspace-by`

**Comment by fool** [comment]
I realize this issue is long-fallow, but I think two things are going on here:

1) we aren't going to install the libraries necessary to build the pg gem which is the proximate cause of our automatic bundler command fail.  I understand this is not what you requested, but it would "work" for some version of work if they were there :)
2) we need to allow you to set flags to `bundle install`, so I have opened a new enhancement request to do this:  https://github.com/netlify/build-image/issues/85
