### ISSUE TITLE
readme states to use build:xenial - script runs build:latest

### ISSUE THREAD

**Issue by nickteeple** [netlify/build-image#402]
readme states to `docker pull build:xenial` and run start-image.sh. When I run start-image.sh, docker ignores build:xenial and pulls build:latest which has older software defaults like ruby 2.4 instead of 2.6

latest docker for windows
launching from within ubuntu 16.04 windows WSL

**Comment by nickteeple** [comment]
this change forced xenial to be used

> $ tail test-tools/start-image.sh  -n1
>         netlify/build:xenial /bin/bash

**Comment by vbrown608** [comment]
Nice catch, thanks for reporting!
