### ISSUE TITLE
Issue with `nvm install --no-progress`

### ISSUE THREAD

**Issue by ehmicky** [netlify/build-image#403]
Due to the nvm progress bar not being shown correctly, [we have been adding](https://github.com/netlify/buildbot/issues/601#issuecomment-620136525) the `--no-progress` CLI flag to `nvm`.

This was done in #400.

However @nickteeple [is reporting](https://github.com/netlify/buildbot/issues/601#issuecomment-620136525) the following:

> this seems to break things FYI. running docker on windows via windows WSL ubuntu 16.04

    buildbot@ff46eac66781:/$ build
    Cloning into '/opt/buildhome/repo'...
    done.
    Installing dependencies
    grep: unrecognized option '--no-progress'
    Usage: grep [OPTION]... PATTERN [FILE]...
    Try 'grep --help' for more information.
    grep: unrecognized option '--no-progress'
    Usage: grep [OPTION]... PATTERN [FILE]...
    Try 'grep --help' for more information.
    Version '--no-progress' not found - try nvm ls-remote to browse available versions.
    Failed to install node version '10'

> if i remove --no-progress it works fine
> $ docker -v
> Docker version 19.03.8, build afacb8b7f0

`--no-progress` requires [`nvm@0.34.0`](https://github.com/nvm-sh/nvm/releases/tag/v0.34.0). However this is [the version we happen to be using](https://github.com/netlify/build-image/blob/0749a9c850ad21598a9c66af181cce606a799e7c/Dockerfile#L278), so all is good there.

But the [following similar issue](https://github.com/nvm-sh/nvm/issues/1663) on the `nvm` repository seems to indicate that this might be due to using the wrong version of `nvm`.

This could very well be a Windows WSL issue as well.

@nickteeple, do you have some additional information?

**Comment by nickteeple** [comment]
ah, i think it's because of the other thing I just reported: https://github.com/netlify/build-image/issues/402

If I run xenial instead of latest it seems to work fine. safe to close.
