### ISSUE TITLE
Update libvips?

### ISSUE THREAD

**Issue by KyleAMathews** [netlify/build-image#42]
Any reason you're using such an old (2 years) version?

**Comment by rybit** [comment]
We don't have a reason, but we don't have a site or anything using it so I am hesitant to update without this. Happy to push it once we do have one though. 8.4.2 work?

**Comment by KyleAMathews** [comment]
Yeah anything newer would be nice. My main user of it, Sharp, downloads a pre-compiled binary so it's not pressing for me. http://sharp.dimens.io/en/stable/install/

**Comment by dubcanada** [comment]
Gatsby & node sharp use 8.5.5 at least.

**Comment by mikestopcontinues** [comment]
I would really appreciate the upgrade. Sharp does install a local version, but when you have multiple packages that require sharp, it seems to only install the first version's libvips, so it was causing problems anyway.

I'm opening an issue with sharp and with the dep in question in any case.

**Comment by fool** [comment]
@brycekahle can we get that PR from @patrick91 merged the during the next roll-out please?
