### ISSUE TITLE
Add Docker image size change to PRs

### ISSUE THREAD

**Issue by vbrown608** [netlify/build-image#441]
When we evaluate PRs to this repo, we want to able to easily answer the question, "how much would this add to the size of our build image?" We could create a github action to add that information to the PR.

**Comment by verythorough** [comment]
Adding to discovery for speedy builds. Also linked in the appropriate section of the [solutions research doc](https://www.notion.so/netlify/Solutions-research-817afa65f3174d8ea58b067e91562ede#fce58d65a1294b08a4b3c0173794d2ba).

**Comment by vbrown608** [comment]
Closed by #516
