### ISSUE TITLE
Feature request: Add PNPM support

### ISSUE THREAD

**Issue by jcayzac** [netlify/build-image#447]
**Which problem is this feature request solving?**

[pnpm](https://pnpm.js.org/) is a robust, mature dependency manager for Node.js projects, and is much faster than npm and yarn. It elegantly [solves npm doppelgängers problem and has stricter module resolution, solving yarn ghost modules](https://rushjs.io/pages/maintainer/package_managers/).

Currently, Netlify users need to use [workarounds](https://community.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759/4) in order to use pnpm, involving altering a proper project configuration and making it less optimal.

**Describe the solution you'd like**

Build images should have `pnpm@latest` preinstalled as a global npm module.
If a `pnpm-lock.yaml` file is detected in the `build.base` folder, `pnpm install --frozen-lockfile` should be run instead of `npm install` (or even better, the _install command_ should just be exposed as a configuration value so that people can run what they want instead of `npm install`).

**Can you submit a pull request?**

~Yes~ ~No~ Maybe.

**Comment by ehmicky** [comment]
Hi @jcayzac,

This sounds good!

Would you like to submit a PR?

**Comment by erquhart** [comment]
Closing - details here: https://github.com/netlify/build-image/pull/449#issuecomment-665674824

Please follow https://github.com/netlify/build/issues/1633 for more.
