### ISSUE TITLE
Cache isn’t available to deploy previews

### ISSUE THREAD

**Issue by jlengstorf** [netlify/build-image#480]
I am creating and caching a file and getting confirmation from the utils that it was cached, but it's not there on subsequent pushes to that PR

this log shows a cache miss, despite confirmation that the cache was created in the previous deploy (you can see the confirmation again, as well as a quick read of the file contents to make sure they're actually there, in the bottom of this log)
https://app.netlify.com/sites/modest-murdock-9912c4/deploys/5eae49da1063950007a54613

source code: https://github.com/jlengstorf/netlify-plugin-applitools-demo/tree/feat/netlify-plugin-high-five/netlify-plugin-en-corg-agement

**Comment by kaganjd** [comment]
Netlify Support here 👋🏻  Exciting update: this has been fixed 🎉 

Check out the community post for more details: https://community.netlify.com/t/build-cache-is-now-updated-in-deploy-preview-builds/26344
