### ISSUE TITLE
NPM_FLAGS doesn't handle more than one flag

### ISSUE THREAD

**Issue by kaganjd** [netlify/build-image#496]
[Someone in Community](https://community.netlify.com/t/how-to-set-npm-flags-environment-variable-properly/25552/) ran into an issue setting NPM_FLAGS to `--verbose --only=prod`. The deploy logs show this error:
```
2:48:54 PM: npm WARN invalid config only="prod --verbose" set in command line options
2:48:54 PM: npm WARN invalid config Must be one of: null, dev, development, prod, production
```
which looks like what should have been `npm install --verbose --only=prod` became `npm install only="prod --verbose" `

When I made a repro, I found that setting NPM_FLAGS to either `--verbose` or `--only=prod` worked, but when both were set, neither worked. Both also worked as expected locally.

**Comment by nolessafool** [comment]
While this may kinda be working as designed - the build-image shell script is full of interesting shell tricks that lead to situations like this -  I think we can all agree that it is not working as anyone would intend, so we called it a bug.  Feel free to disagree and change to type: feature and remove from your board.

**Comment by JGAntunes** [comment]
Hey folks 👋

FYI, thanks to @celinepelletier's awesome contribution this has been fixed and rolled out to both our `xenial` and `focal` releases. (An example log of the `NPM_FLAGS` correctly applied - https://app.netlify.com/sites/ntfy-init-test/deploys/60f19800d603753ea8b6a6a6#L10780)
