### ISSUE TITLE
#477 seems to have broken `cargo doc`-based documentation previews

### ISSUE THREAD

**Issue by davidbarsky** [netlify/build-image#505]
Hello! The (extremely welcome!) changes in #477 appears to have broken our (relatively niche) use-case where we generate documentation previews for each PR send to `tokio-rs/tracing`. I suspect that with the deployment of #447, the `target` directory that's generated by Cargo is no longer available to `publish` step. This is problematic for us as we use contents of `target/doc` as the deployable documentation preview. In my attempts to debug the deployment failures we're seeing (https://github.com/tokio-rs/tracing/pull/1130), I've developed the following theory:

1. The `cache_cwd_directory` function ([callsite](https://github.com/cecton/build-image/blob/23b30a7e4e3fc25bef908c25b911158b53f4e86d/run-build-functions.sh#L678), [definition](https://github.com/cecton/build-image/blob/23b30a7e4e3fc25bef908c25b911158b53f4e86d/run-build-functions.sh#L755-L757)) moves Cargo's build output to `$NETLIFY_CACHE_DIR`.
2. `cache_cwd_directory` calls [`move_cache`](https://github.com/cecton/build-image/blob/23b30a7e4e3fc25bef908c25b911158b53f4e86d/run-build-functions.sh#L739-L749), which removes the Cargo-generated `target` directory. 

Contemporaneously with https://github.com/netlify/build-image/pull/477#issuecomment-741384078 being posted, we've started noticing the site build errors contain the message "Deploy directory 'target/doc' does not exist". Here's the first build where I've noticed this: https://app.netlify.com/teams/tokio/builds/5fd051070a10d60007567df3.

Anyways, thanks so much for this service! I'm pretty sure this is the first we've ever had to reach out for support!

**Comment by mraerino** [comment]
this is unfortunate, i'm sorry. we actually have a special flag enabled internally which moves caching after the upload step so we didn't see it for ourselves.

for now the workaround will be to manually copy the docs outside of `target`, but i'll try to get a fix in so that we don't move those files.

**Comment by cecton** [comment]
If you are on a filesystem that supports it you can use CoW instead of move:

```
# copy super fast
cp --reflink=always source/ destination/
```

https://www.man7.org/linux/man-pages/man1/cp.1.html

It will be as fast as the move you do but it copies instead so both stay accessible.

cc @mraerino
