### ISSUE TITLE
Bug: 'target' can't be a deploy directory anymore

### ISSUE THREAD

**Issue by mainej** [netlify/build-image#508]
I have a project that compiles into the `target` directory, a sub-directory of my repo. My site is configured to use `target` as the 'deploy' directory (aka the 'publish' directory, I think.) This was working until recently. 

Recent changes to this `netlify/build-image` mean that it assumes every project is a rust project, regardless of whether the project uses rust, and that therefore `target` is cache-able. You can see this by `git blame`ing the following line: https://github.com/netlify/build-image/blob/53b83b6bede2920f236b25b6f5a95334320dc849/run-build-functions.sh#L678

After my build finishes (successfully), the caching code `mv`s the `target` directory. See this line: https://github.com/netlify/build-image/blob/53b83b6bede2920f236b25b6f5a95334320dc849/run-build-functions.sh#L746

Because of this, the `/opt/buildhome/repo/target` directory doesn't exist when the deploy starts, and the build fails with the log message "Failed during stage 'building site': Deploy directory 'target' does not exist".

I can think of a few fixes:
1. The build functions could check whether the project uses rust before trying to cache the `target` directory.
2. The build could run the deploy before starting the caching.
3. The caching code could `cp` the cacheable directories, instead of `mv`ing them.
4. The [Support Guide](https://community.netlify.com/t/support-guide-frequently-encountered-problems-during-builds/213) could document forbidden deploy directories.

In the meantime, I'll try to compile to a different directory.

I was able to debug this using the docker image. My prior attempts to fix the problem are documented in [this support ticket](https://community.netlify.com/t/deploy-directory-target-does-not-exist/28413).

**Comment by mainej** [comment]
Confirmed: after changing the build (aka publish) directory from `target` to `release`, my site deployed successfully.

**Comment by changke** [comment]
Can confirm. The directory name "target" is kind of "reserved".
