### ISSUE TITLE
Typo when cancelling

### ISSUE THREAD

**Issue by davidsneighbour** [netlify/build-image#528]
I am not sure if this belongs here, please move around if this is related to something else.

I am pretty sure "Canceling" needs to be spellt (pun intended) "Cancelling"

![Selection_116](https://user-images.githubusercontent.com/83281/109021089-22e9b380-76ed-11eb-8734-833cd2ce95de.png)

**Comment by ehmicky** [comment]
Hi @davidsneighbour,

Thanks for reaching out.
Both spellings seem to be correct. This might be a US vs UK distinction.
https://en.wiktionary.org/wiki/cancelling

What are your thoughts on this @rstavchansky ?

**Comment by davidsneighbour** [comment]
Wow, this is new to me :(

https://books.google.com/ngrams/graph?content=canceling%2C+cancelling&year_start=1800&year_end=2009&corpus=5&smoothing=3&direct_url=t1%3B%2Ccanceling%3B%2Cc0%3B.t1%3B%2Ccancelling%3B%2Cc0#t1%3B%2Ccanceling%3B%2Cc0%3B.t1%3B%2Ccancelling%3B%2Cc0

Looks like Canceling is quite ok. If all responses are AE ;) So no socialising, but always socializing. "it is what it is" ;(

**Comment by rstavchansky** [comment]
We use Merriam Webster to confirm American English usage for spelling, and yes, they include both options. So, I agree that what we currently have is fine.
https://www.merriam-webster.com/dictionary/canceling

**Comment by ehmicky** [comment]
Thanks @rstavchansky.
I am closing this issue, thanks for raising it @davidsneighbour :pray:
