### ISSUE TITLE
Plan for Ubuntu 16.04 end of life at the end of this month?

### ISSUE THREAD

**Issue by ab** [netlify/build-image#541]
Ubuntu 16.04 (Xenial) reaches end of life at the end of this month, April 30 2021. At that time it will no longer receive free security or maintenance updates. Is there a transition plan for Netlify build images? It doesn't look like there is currently any Netlify image based on a newer Ubuntu release.

Thanks!

https://ubuntu.com/about/release-cycle
https://wiki.ubuntu.com/Releases

**Comment by mortenson** [comment]
It'd be great to get an image with 20.04 as well - right now Tome (a small static site generator I maintain) doesn't work on the 16.04 image when using Drupal 9 because of a new requirement for SQLite 3.26+. Getting a new version of SQLite working with 16.04 / 18.04 is pretty complex.

**Comment by JanSichula** [comment]
It looks like new version 4.0 will be based on Ubuntu 20.04 which is obvious from prerelease build.

**Comment by kitop** [comment]
Late update here, but Ubuntu Focal (20.04) has been released! https://answers.netlify.com/t/new-ubuntu-20-04-focal-fossa-build-image/37095

You should be able to update the image in your site settings page, in the "Build & Deploy" section.

We will be fully deprecating Xenial image soon, but want to give time for people to update. Please follow the ["Updates" section of the forums](https://answers.netlify.com/c/features/updates/51) for news.
