### ISSUE TITLE
Make default Ruby version match installed Ruby version

### ISSUE THREAD

**Issue by danielcompton** [netlify/build-image#601]
I'm not quite sure how this is happening, but I've observed that Ruby 2.7.1 is the default ruby, but it's not installed in the environment. For example:

```
1:36:56 PM: Attempting ruby version 2.7.1, read from environment
1:36:57 PM: Required ruby-2.7.1 is not installed - installing.
1:36:58 PM: Searching for binary rubies, this might take some time.
1:36:58 PM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.1.tar.bz2
1:36:58 PM: Checking requirements for ubuntu.
1:36:59 PM: Requirements installation successful.
1:36:59 PM: ruby-2.7.1 - #configure
1:36:59 PM: ruby-2.7.1 - #download
1:37:00 PM: ruby-2.7.1 - #validate archive
1:37:06 PM: ruby-2.7.1 - #extract
1:37:09 PM: ruby-2.7.1 - #validate binary
1:37:09 PM: ruby-2.7.1 - #setup
1:37:10 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1@global
1:37:10 PM: ruby-2.7.1 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems........................................
1:37:11 PM: ruby-2.7.1 - #generating global wrappers........
1:37:11 PM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1
1:37:11 PM: ruby-2.7.1 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
1:37:12 PM: ruby-2.7.1 - #generating default wrappers........
1:37:12 PM: Using /opt/buildhome/.rvm/gems/ruby-2.7.1
1:37:13 PM: Using ruby version 2.7.1
```

Running a second time restores the cached Ruby which is better but not ideal.

```
1:39:10 PM: Attempting ruby version 2.7.1, read from environment
1:39:11 PM: Started restoring cached ruby version
1:39:11 PM: Finished restoring cached ruby version
1:39:13 PM: Using ruby version 2.7.1
```

This seems to happen with both 16.04 and 20.04.

I would expect that the default RUBY_VERSION is installed in the build image. It appears like it should be, so I'm not quite sure what is happening? I don't use any Ruby tools. I added a RUBY_VERSION = "2.6.2" which seemed to fix the issue.

Possibly 2.7.1 should be updated to 2.7.2 as that's the version that's being installed now alongside 2.6.2?

https://github.com/netlify/build-image/blob/4e4f0f30093124b52150081b2519828364ba1bd6/run-build.sh#L22

https://github.com/netlify/build-image/blob/bfcce1e4353253130a555613aa3eff944465da54/Dockerfile#L237-L240

**Comment by kitop** [comment]
This is now matching
https://github.com/netlify/build-image/blob/7f982ee89631b4cd9ccab6cfd948ec9a7fb242cf/run-build.sh#L22
https://github.com/netlify/build-image/blob/7f982ee89631b4cd9ccab6cfd948ec9a7fb242cf/Dockerfile#L230-L236
