### ISSUE TITLE
Yarn default binary not added to the user's $PATH

### ISSUE THREAD

**Issue by JGAntunes** [netlify/build-image#640]
The yarn binary installed by default within the build image (see [here](https://github.com/netlify/build-image/blob/focal/Dockerfile#L263)) isn't part of the users `$PATH` by default. This means that for builds which don't have a cached version of yarn, there will always be a download of the default version of yarn for that site (which takes care of correctly setting the user's `$PATH` - see [here](https://github.com/netlify/build-image/blob/focal/run-build-functions.sh#L110)) without it actually being required, because our yarn version check will essentially fail (see [here](https://github.com/netlify/build-image/blob/focal/run-build-functions.sh#L104)).

E.g. this [build](https://app.netlify.com/sites/gatsby-yarn-test/deploys/615712a010ac3e00e2b0b266) is a fresh one, with a clean cache, using focal, which comes packed with yarn version `1.22.10`. Yet, we ended up installing that version again.

**Comment by ascorbic** [comment]
We hit this with the default Nuxt 3 starter, because it uses yarn in the build command but doesn't commit the `yarn.lock`

**Comment by JGAntunes** [comment]
This has now been shipped 👍
