### ISSUE TITLE
Python 3.7 deployment errors?

### ISSUE THREAD

**Issue by kcgthb** [netlify/build-image#667]
Deployment failed today with:
```
Starting build script
3:41:53 PM: Installing dependencies
3:41:53 PM: /opt/build-bin/run-build-functions.sh: line 205: /opt/buildhome/python3.7/bin/activate: No such file or directory
3:41:53 PM: Error setting python version from runtime.txt
3:41:53 PM: Please see https://github.com/netlify/build-image/#included-software for current versions
3:41:53 PM: Build was terminated: Build script returned non-zero exit code: 1
```
My `runtime.txt` contains:
```
3.7
```
Is this expected?

The  https://github.com/netlify/build-image/#included-software doesn't seem to exist either :\

**Comment by JGAntunes** [comment]
Hey @kcgthb 👋

Could you share which build-image version you're using? It should be logged at the beggining of your deployment logs.

- Focal (v3) supports `3.8` and `2.7` - https://github.com/netlify/build-image/blob/focal/included_software.md
- Xenial (v4) supports `2.7`, `3.5` and `3.7` - https://github.com/netlify/build-image/blob/xenial/included_software.md

> The https://github.com/netlify/build-image/#included-software doesn't seem to exist either :\

💯. We're working on improving those logs specifically via #616. Sorry if this caused some confusion 🙏

**Comment by kcgthb** [comment]
Hi @JGAntunes, thanks for getting back to me!

> Could you share which build-image version you're using? 

I think the default, I wasn't specifying any particular version, my only config file was the `runtime.txt` file:
```
3:48:34 PM: build-image version: 3bcb38c35508b42e9121d4badfe6d8c66fd7a3f0
3:48:34 PM: build-image tag: v4.3.2
```
I managed to solve the issue by replacing `3.7` with `3.8` in `runtime.txt`, I guess that the default image changed at some point and Python 3.7 was dropped.

Anyway, problem solved now, thanks!
