### ISSUE TITLE
Add Vips CLI tools (libvips-tools)

### ISSUE THREAD

**Issue by SebouChu** [netlify/build-image#681]
Currently, the Focal image installs libvips-dev but not libvips-tools, which prevents Jekyll plugins like [Jekyll Picture Tag](https://github.com/rbuchberger/jekyll_picture_tag) to work properly.

It seems to be a regression from the Xenial image, which installed Vips [from source](https://github.com/netlify/build-image/blob/649f3866bbbdb310033ee494eb7123b5b6df2d0b/Dockerfile#L202) and so, had the CLI tools with it.

I [forked](https://github.com/SebouChu/build-image) the repo to add the dependency with a bats test to check if vips is available. I can make a PR whenever you need!

Thanks in advance for your feedback!

**Comment by JGAntunes** [comment]
Hey @SebouChu 👋 thanks for raising this. Yeah a PR would be awesome 👍

**Comment by JGAntunes** [comment]
Reopening this issue while we don't fully ship it to prod. Will keep you updated 👍

**Comment by JGAntunes** [comment]
Hey @SebouChu sorry for the delay. We've just released this to production this afternoon so it should be fixed on the latest `focal` builds 👍 Let us know if that didn't cut it and thanks once again for your contribution! 🎉
