### ISSUE TITLE
Focal image installs Node 12.18.0 instead of 16 specified in docs

### ISSUE THREAD

**Issue by swrobel** [netlify/build-image#693]
The [Focal image docs](https://github.com/netlify/build-image/blob/focal/included_software.md) specify Node 16 by default. Without any sort of config specifying a node version, I would then expect Node 16 to be installed. However, I get 12.18.0 instead:

```
10:33:38 AM: Build ready to start
10:33:40 AM: build-image version: 8925038cf853b22d6397cdcb9904ac88b66bb383 (focal)
10:33:40 AM: build-image tag: v4.5.0
10:33:40 AM: buildbot version: 8b4b13a586b9f817ab478c0c44a476554bc16a2f
10:33:40 AM: Building without cache
10:33:40 AM: Starting to prepare the repo for build
10:33:41 AM: No cached dependencies found. Cloning fresh repo
10:33:41 AM: git clone https://github.com/...
10:33:46 AM: Preparing Git Reference refs/heads/main
10:33:46 AM: Parsing package.json dependencies
10:33:47 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
10:33:47 AM: Starting build script
10:33:47 AM: Installing dependencies
10:33:47 AM: Python version set to 2.7
10:33:48 AM: Downloading and installing node v12.18.0...
10:33:48 AM: Downloading https://nodejs.org/dist/v12.18.0/node-v12.18.0-linux-x64.tar.xz...
10:33:49 AM: Computing checksum with sha256sum
10:33:49 AM: Checksums matched!
10:33:51 AM: Now using node v12.18.0 (npm v6.14.4)
```

**Comment by JGAntunes** [comment]
Hey @swrobel 👋

By default, your site should also have a pinned Node.js version that overrides the one installed by default in the `build-image`, you can read more about that behaviour in the following community post - https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004#how-can-i-make-my-site-work-with-the-new-image-6 (quoting below but feel free to check the post for all the relevant links):
> Note: if the dependency version was not explicitly set by you, then it’s set to a version selected by default when you created your site. You can override this as described in the dependency management docs 45. Select a version already installed on the image 193 to avoid unneeded installations.
> If you prefer not to set a version explicitly, you can “reset” your site defaults by re-linking your site repository 1, but please note that this will also remove any environment variables set in the Netlify UI. Be sure to copy your variables before re-linking, then re-enter them after re-linking.

Hope it helps. Closing this issue as it's unrelated with the `build-image` repo 👍

**Comment by swrobel** [comment]
For anyone else who just wants latest LTS on the Focal image, this trick worked for me and didn't require manually specifying a node version: https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004/23
