### ISSUE TITLE
Add Support for .NET 6

### ISSUE THREAD

**Issue by lucaswalter** [netlify/build-image#694]
We use Netlify to build and deploy our Blazor site (which runs on .NET). Microsoft just released and published the GA version of .NET 6 which we would like to use:

https://devblogs.microsoft.com/dotnet/announcing-net-6/

**Comment by atheken** [comment]
Based on the source code in this repo, I did the following and was able to get .net6 builds working. It adds about 1m to the build time, but is a temporary fix until a new image is released by Netlify:

```

#!/usr/bin/env bash
set -e

## install latest .net until a new netlify image is released...
pushd /tmp
wget https://dot.net/v1/dotnet-install.sh
chmod u+x /tmp/dotnet-install.sh
/tmp/dotnet-install.sh -c Current
dotnet new
popd

dotnet --info

... build commands...
```

Hope that gets you going. Should be temporary.

**Comment by krompaco** [comment]
@atheken Interesting! Where do I put those commands?

Also... Is this normal time before someone picks up an issue?

Would also be nice to add dotnet and which versions are in there etc to the documentation here for example: https://github.com/netlify/build-image/blob/focal/included_software.md

Just the output of `dotnet --list-sdks` would do.

I think it would be great to have both a 5.0 and 6.0 installed so that authors can choose by adding a `global.json` file.

**Comment by atheken** [comment]
I don’t actually work at Netlify, I just wanted to get my build working.

To answer your questions: I include a single bash script in my repo, something like “./scripts/build.sh” and then configure Netlify to run that script, that’s where the snippet above goes.

//Andrew

**Comment by liamgold** [comment]
Pretty sure this is done now, I had to upgrade my website from .NET 5 to .NET 6 as the build agent no longer supported .NET 5:

```
10:11:59 PM: The framework 'Microsoft.AspNetCore.App', version '5.0.0' (x64) was not found.
10:11:59 PM:   - The following frameworks were found:
10:11:59 PM:       6.0.0 at [/opt/buildhome/.dotnet/shared/Microsoft.AspNetCore.App]

**Comment by atheken** [comment]
Yeah, it looks like Netlify did a [release of the image 2 days ago](https://github.com/netlify/build-image/commit/a6bb34428a07e7de82f4df5dfe1843fbde91f670), and like I said based on the scripts, the build pulls the latest SDK for .net. I ran my build and now am seeing:

```

6:59:58 AM: $ dotnet --info
6:59:58 AM: .NET SDK (reflecting any global.json):
6:59:58 AM:  Version:   6.0.100
6:59:58 AM:  Commit:    9e8b04bbff
6:59:58 AM: Runtime Environment:
6:59:58 AM:  OS Name:     ubuntu
6:59:58 AM:  OS Version:  20.04
6:59:58 AM:  OS Platform: Linux
6:59:58 AM:  RID:         ubuntu.20.04-x64
6:59:58 AM:  Base Path:   /opt/buildhome/.dotnet/sdk/6.0.100/
<snip>
```

**Comment by JGAntunes** [comment]
Hey folks 👋 thanks for raising this. As @atheken mentioned seems like the latest release has shipped an unintended update to the `.NET` version installed. Created #706 to track a fix for it.

As for supporting multiple versions we currently have no plans to tackle that straight away, however if that is work you would be interested in seeing done feel free to open an issue or a PR to add support for such 👍

Closing this issue.

**Comment by nde-agridea** [comment]
> I don’t actually work at Netlify, I just wanted to get my build working. To answer your questions: I include a single bash script in my repo, something like “./scripts/build.sh” and then configure Netlify to run that script, that’s where the snippet above goes. //Andrew

How do you do that (configure Netlify to run that script) ? Nowhere could I find an option in the UI to run a custom script. Thanks.
