### ISSUE TITLE
Can't build image on Apple Silicon

### ISSUE THREAD

**Issue by akahn** [netlify/build-image#715]
[Some](https://github.com/netlify/build-image/blob/focal/Dockerfile#L303-L305) [places](https://github.com/netlify/build-image/blob/focal/Dockerfile#L194-L203) in the `Dockerfile` hard-code the architecture of installed packages as `amd64`. On an Apple computer with M1 (arm64) architecture, this produces the following error:

```
#6 2.597  package architecture (amd64) does not match system (arm64)
```

We should update these install commands to use one of the [Docker built-in variables](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope), such as `TARGETARCH`. This way, the packages will be installed according to the architecture of the Docker engine. 

There may also be other issues M1 users face after this, the immediate problem, is solved.

**Comment by akahn** [comment]
In addition to the above issue, there is an issue with `segmentation fault`s with curl/libssl on Ubuntu 20.04. The [Docker for Mac release notes](https://docs.docker.com/desktop/mac/release-notes/3.x/#known-issues) advise upgrading to Ubuntu 21.04. There is no other fix or workaround suggested.

**Comment by juanpprieto** [comment]
+1
