### ISSUE TITLE
chore(ci): Xenial CircleCI pipeline is broken

### ISSUE THREAD

**Issue by erezrokah** [netlify/build-image#731]
See PRs:
https://github.com/netlify/build-image/pull/726
https://github.com/netlify/build-image/pull/730

and failures:
https://app.circleci.com/pipelines/github/netlify/build-image/234/workflows/cd621357-e89e-429a-bb76-185f3fc4348b/jobs/641
https://github.com/netlify/build-image/runs/4883672971?check_suite_focus=true

**Comment by aitkenster** [comment]
Pretty sure this is the root cause: [No more support for Ubuntu 16.04 Xenial](https://github.com/deadsnakes/issues/issues/195)

**Comment by erezrokah** [comment]
Can we close this as resolved? Not sure why merging https://github.com/netlify/build-image/pull/736 didn't close it.

**Comment by erezrokah** [comment]
Closing, please re-open if needed
