### ISSUE TITLE
Schedule periodical CI executions

### ISSUE THREAD

**Issue by JGAntunes** [netlify/build-image#735]
Schedule periodical CI executions (daily?) to help us detect problems like https://github.com/netlify/build-image/issues/731 sooner instead of spotting it during a particular release or fix.

**Comment by kitop** [comment]
@JGAntunes with CircleCI this is quite easy to do with triggers. We'd probably want to avoid the push to registry step though, right?
If so, we can add some [conditionals](https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows) to just run the test parts.

If you confirm, I'm happy to look into it.

**Comment by JGAntunes** [comment]
Yep exactly @kitop. We can run the test and build phase only, daily (setup with triggers). We should also setup notifications for CCI to our slack channels so that we can track possible pipeline failures.

**Comment by kitop** [comment]
Thanks! I'll start looking into this
