### ISSUE TITLE
Can't find Python 3.7 on Xenial when specified via Pipfile

### ISSUE THREAD

**Issue by verythorough** [netlify/build-image#739]
**Is your build failing?**

If a site includes a `Pipfile` requiring Python 3.7, yes, the build fails.

**Describe the bug**

On Zenial, Python is available in version 2.7 (default), 3.5, and 3.7. There are [three methods](https://docs.netlify.com/configure-builds/manage-dependencies/#python) for choosing the version: `PYTHON_VERSION`, `runtime.txt`, and `Pipfile`. All three methods work to specify 2.7 or 3.5, but if you require version 3.7 in a `Pipfile`, it prints this message: `Warning: Python 3.7 was not found on your system...` Then it errors out installing pipenv dependencies and fails the build.

**To Reproduce**

I made a repro repo: https://github.com/verythorough/python-tester

Here's a failing build from the main branch with 3.7 specified via Pipfile:
https://app.netlify.com/sites/pipfile-tester/deploys/620361355a170c0007428e22#L28

Here's a successful build with 3.5 set via Pipfile:
https://app.netlify.com/sites/pipfile-tester/deploys/620361885a170c0007428e40

And here's a successful build with 3.7 set via runtime.txt:
https://app.netlify.com/sites/pipfile-tester/deploys/620363495fcddf000723ae2f#L14

**Configuration**

You can check the deploy settings at https://app.netlify.com/sites/pipfile-tester/settings/deploys

**Additional context**

Might be related to https://github.com/netlify/build-image/pull/736.

Obviously since this is Xenial, it's not worth investing too much in fixing this. A possible mitigation could be just to update the `included_software.md` file to note that 3.7 can't be specified via Pipfile (in the Xenial version only).

**Comment by kitop** [comment]
Closing this as the Xenial image is going to be deprecated: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
We're unlikely to investigate this. If it happens against focal, please re-open and provide an updated description.
