### ISSUE TITLE
update ruby version

### ISSUE THREAD

**Issue by notghettolenny** [netlify/build-image#783]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. 
the version of ruby being used is ruby 2.7 : ${RUBY_VERSION="2.7.2"}

**Describe the solution you'd like**
update to latest ruby version 3.1

**Describe alternatives you've considered**

**Additional context**

**Can you submit a pull request?**

Yes/No.

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by kitop** [comment]
@notghettolenny you can set the ruby version of your build in Netlify by setting a `RUBY_VERSION` environment variable or  having a `.ruby-version` file. More details in docs: https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

Closing this as that should solve the issue for a site. Please reopen with more details if this doesn't solve it.
