### ISSUE TITLE
Node versions

### ISSUE THREAD

**Issue by grifotv** [netlify/build-image#8]
Is there a reason for Netlify to have a limited amount of Node versions available?
https://github.com/netlify/build-image/blob/54bc484b98e83e16ac905764b98379bceeda46ae/Dockerfile#L96-L141

It would be great if it would be in sync with all releases, just like NVM
https://nodejs.org/en/download/releases/

Thanks!

**Comment by hhsnopek** [comment]
@grifotv in the future there will be this ability to just specify the version of node you'd like to use... but for now there's a limited amount until #15 is added in so you may use any lts version or the latest

**Comment by fool** [comment]
I think you can now nvm use any version and we will pull it down.  If someone has evidence to the contrary, please reopen!
