### ISSUE TITLE
Support code in subdirectory of repo

### ISSUE THREAD

**Issue by r1b** [netlify/build-image#81]
I have a gatsby app - it lives in the `site/` directory of my repo. When I attempt to build the app with netlify I get:

`/opt/build/build.sh: line 427: gatsby: command not found`

I believe this is because `npm install` is never successfully run - when it runs it finds no `package.json` in the repo root.

Is it currently possible to build a subdirectory of the repo?

**Comment by r1b** [comment]
CircleCI has an option called `build_dir` for this use case:

https://circleci.com/docs/1.0/configuration/#build-dir

**Comment by fool** [comment]
There is a configuration option for this already in our netlify.toml file:

https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

Specifically the "base" setting is a "cd here and then run my build command".  As a bonus it also makes dependency caching work right ;)

**Comment by ferhatelmas** [comment]
@fool I have a monorepo and how can I specify configuration for multiple different sites ?

**Comment by khrome83** [comment]
@fool - any ETA on when the interface for this will be completed? If I am not on a paid plan will support@netlify.com help with this?

**Comment by fool** [comment]
No need to be paid, @khrome83 !  Just ping us in the helpdesk.

There's no ETA for this - just some open feature requests.

**Comment by pdeka** [comment]
@fool It would be fabulous to have the ability to deploy multiple apps in a monorepo through the deploy UI. Please keep us updated on the progress of this feature.

**Comment by sw-yx** [comment]
this is hacky but you can basically set up multiple sites separately for a monorepo: demo here https://github.com/sw-yx/TwoSitesOneRepo

**Comment by wahidshafique** [comment]
@sw-yx  > this is hacky but you can basically set up multiple sites separately for a monorepo: demo here https://github.com/sw-yx/TwoSitesOneRepo

What about subdirectories on the same domain? Something like
https://twositesonerepo.com/site1
https://twositesonerepo.com/site2

**Comment by sw-yx** [comment]
oh thats even easier. https://www.netlify.com/docs/redirects/

**Comment by bkniffler** [comment]
Any news on this? I'd love to have acces via UI.

**Comment by sw-yx** [comment]
cc @bcomnes - i dont have access to this repo to reopen this but fool says Mat likes the idea - need to scope out what needs to be done on the build side of things as i have no clue

**Comment by whaaaley** [comment]
I'm also looking for this. I'm trying to do what was suggested above but manually running `npm i` isn't working for some reason... 🤔

**Comment by adekbadek** [comment]
@sw-yx could you please show how the "multiple sites separately for a monorepo" configuration is set up in netlify UI? I've added [an issue in your example repo](https://github.com/sw-yx/TwoSitesOneRepo/issues/1). Thanks!

**Comment by swyxio** [comment]
literally deploy the same repo twice...
![image](https://user-images.githubusercontent.com/6764957/54400123-87391700-467e-11e9-8d31-0baaddff5c7a.png)

and use different build commands...

![image](https://user-images.githubusercontent.com/6764957/54400136-9a4be700-467e-11e9-840b-0457353a3dc5.png)
![image](https://user-images.githubusercontent.com/6764957/54400142-a768d600-467e-11e9-9b2f-626d01fb530f.png)


if you have @wahidshafique's usecase, you can also set up a redirect from your main site to the sub site

**Comment by adekbadek** [comment]
oh, nice! and doesn't really feel "hacky", as these in fact separate `sites`. thanks!

**Comment by chrisgalvan** [comment]
Any news on this? I'd love to have access via UI.

**Comment by andreasvirkus** [comment]
Issue with the proposed solutions is that they'll always trigger a build for both sites, which is obviously undesirable

Edit: seems there's an official solution now 🎉 
https://www.netlify.com/blog/2019/10/09/launching-monorepo-support-for-netlify-sites/
