### ISSUE TITLE
Install `exiftool`?

### ISSUE THREAD

**Issue by fortes** [netlify/build-image#84]
I've got a project that depends on [`exiftool`](https://www.sno.phy.queensu.ca/~phil/exiftool/), would love to know if it's possible to install. It's available via `apt` as `libimage-exiftool-perl`

Thanks!

**Comment by fool** [comment]
pull requests welcome :) What you'd need to do is:

- change Dockerfile to include that in an apt-get install step
- verify that the file then builds and your tool is inside
- submit a PR on this repo

**Comment by fortes** [comment]
Created a pull request! #87
