### ISSUE TITLE
Monorepo project cannot found pnpm 

### ISSUE THREAD

**Issue by Dunqing** [netlify/build-image#855]
**Describe the bug**

In the `monorepo` project, the `netlify` configuration files are distributed in different directories, it will not be able to find `pnpm`, if there is `pnpm-lock.yaml` in the `base` directory of that configuration, it will work.

Like the following
```
- apps
  - main
    - netlify.yaml (cannot found `pnpm`)
  - child
    - netlify.yaml (found `pnpm`)
    - pnpm-lock.yaml 
- pnpm-workspace.yaml
```

**Comment by lukasholzer** [comment]
as a workaround you can use the envrionment variable `NETLIFY_USE_PNPM=true` in your envrionment variable settings in the UI. This will force the build to use pnpm.

Already working on this issue

**Comment by Dunqing** [comment]
> as a workaround you can use the envrionment variable `NETLIFY_USE_PNPM=true` in your envrionment variable settings in the UI. This will force the build to use pnpm.

Thank you, the workaround is good for me
