### ISSUE TITLE
node version can get set to none by our scripts, which breaks any npm-based build.

### ISSUE THREAD

**Issue by fool** [netlify/build-image#86]
When:

- you use .nvmrc to set node version and have 6.11.1 in it
- and we save your dependencies
- future builds using those dependencies SOMETIMES fail with these errors:

```
Using version none of node
[...]
/opt/build/build.sh: line 120: npm: command not found
```

This is a link to a message in our (private) slack with a link to a customer's failed deploy example (customer's site name and URL's  includes their business name so not publishing it here)

https://netlify.slack.com/archives/C0QFKKY2U/p1506701906000491

There is no steady repro case - clearing the cache helps "sometimes, for a while" - but the above linked build has verbose logging on so someone on Netlify's team can debug.

**Comment by brycekahle** [comment]
This has been fixed by making cache operations atomic.
