### ISSUE TITLE
No $EDITOR defined

### ISSUE THREAD

**Issue by pixelastic** [netlify/build-image#91]
Hello,

I'm using the image to debug a deploy that is not working as expected (some of my dependencies are not correctly loaded, but this is irrelevant to this issue). Instead of pushing every test commit to Netlify, I'm running the docker image to see where it fails.

In my debugging process, I would also like to edit my scripts to pinpoint where the issue might lie. But I can't find any editor (vim, nano, emacs) available in the image for debugging. The `$EDITOR` variable is also empty.

Am I missing something or would you accept a PR to add vim?

**Comment by rybit** [comment]
Good to know that you're using it to debug. We probably wouldn't take a PR with vim on it. Vim shouldn't really be used during an actual build, and would just be bloat on the image. 

I'd recommend either modifying the image and build/test with it locally or do a shared volume mount where you can modify that file on your local system and it will be reflected in the image.

**Comment by pixelastic** [comment]
Thanks, I cannot currently build the image because of #62, but I think I'll go with the shared volume once that's fixed. Thanks for the info.
