### ISSUE TITLE
Upgrade default version of hugo

### ISSUE THREAD

**Issue by fool** [netlify/build-image#93]
Our current default version of hugo is quite old - almost halfway back in the version history (v0.17 vs current v0.30.2).

Could we do the thing we've done with node wherein we pin the old version for old sites and install a newer version to use by default when someone uses a build command `hugo` on a new site? 

It would be a better user experience as very few new customers showing up today use old hugo.

This would need an associated migration in the database for existing repo settings, and some logic in the build image to respect it, but this seems like the sanest place to track all the work.

Request  by @bep and his posse of thousands of hugo users :)

**Comment by davidpelayo** [comment]
I agree this must be updated asap. I was about to use netlify in my personal site to automate the process and simplify it, but since the version is tool old, [I'll hold this for now](https://github.com/davidpelayo/www/issues/5).

**Comment by inwardmovement** [comment]
I'm not sure to understand: it's possible to force Netlify to use the latest Hugo version even if it's not an available version in the [Netlify’s Docker file](https://github.com/netlify/build-image/blob/master/Dockerfile#L287), simply by writing the version in `netlify.toml` ?

**Comment by bep** [comment]
@inwardmovement yes, see https://github.com/gohugoio/hugoDocs/blob/master/netlify.toml#L6

**Comment by inwardmovement** [comment]
Yes that is what raised my question, because in Hugo docs it's said:
> Setting the build command to hugo will build your site according to the current default Hugo version used by Netlify. You can see the full list of available Hugo versions in Netlify’s Docker file.

which made me think we are bound to Netlify's Hugo version. This was preventing me from using Netlify as I would like to benefit the latest Hugo versions, but it's awesome that we can use whatever version we want, thanks :)

Maybe the Hugo docs should be clarified in regard to this, I can try a PR if you want @gohugoio

**Comment by bep** [comment]
>Maybe the Hugo docs should be clarified in regard to this, I can try a PR if you want @gohugoio

That would be most welcome.

**Comment by fool** [comment]
@inwardmovement I'd suggest referring to this blog post that describes in depth what hugo versions are available on netlify and the two ways you can configure one:

https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/

**Comment by inwardmovement** [comment]
Thanks @fool I added the reference in my [PR](https://github.com/gohugoio/hugoDocs/pull/349)

**Comment by bcomnes** [comment]
Default is 0.54 extended in the xenial image.  This should be done now.
